[package]
name = "broker-ibkr"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["alloc"] }
ibkr-client = { version = "0.1.0", path = "../../ibkr-client" }
trade-control-core = { version = "0.1.0", path = "../core" }
tracing = "0.1"
ibapi = "3.3.0"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt"] }
