//! Render derived contract dates into the committed
//! `core/src/contract_calendar_baked.rs` table for `core` to `include!`.
//!
//! # Row shape
//!
//! `(root, contract_month, settlement, last_trade_day, first_notice_day,
//!   long_close_out, short_close_out)`
//!
//! Dates are `"YYYY-MM-DD"` strings (parsed once at lookup); `first_notice_day`
//! is `""` for cash-settled contracts. `contract_month` is `"YYYYMM"`, matching
//! the form IBKR reports on `ContractDetails`.
//!
//! # Duplicate keys are a hard error, not a silent first-match
//!
//! `core/src/spread_blackout/coverage.rs` and `core/src/intent/blackout/baked.rs`
//! both bind their first column to `_` and take the first symbol match, so a
//! colliding key silently resolves to whichever row sorted first. That shape is
//! deliberately **not** copied here: [`render_table`] returns an error on a
//! duplicate `(root, contract_month)` rather than emitting an ambiguous table,
//! and the lookup side refuses ambiguity too.

use std::collections::BTreeSet;

use crate::rules::{ContractDates, Settlement, spec_for};

/// Rendering failed because the input would produce an ambiguous table.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenderError {
    /// Two rows share a `(root, contract_month)` key. Emitting both would make
    /// lookups depend on row order.
    DuplicateKey { root: String, month: String },
    /// A row's root has no spec — it could not have been derived by this
    /// crate, so something upstream is inconsistent.
    UnknownRoot { root: String },
}

impl std::fmt::Display for RenderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RenderError::DuplicateKey { root, month } => {
                write!(f, "duplicate contract key ({root}, {month})")
            }
            RenderError::UnknownRoot { root } => write!(f, "unknown contract root {root}"),
        }
    }
}

impl std::error::Error for RenderError {}

/// Format a contract month as IBKR reports it: `"YYYYMM"`.
pub fn contract_month(year: i32, month: u32) -> String {
    format!("{year:04}{month:02}")
}

/// Render the derived rows into a Rust source file.
///
/// Rows are sorted by `(root, contract_month)`. A duplicate key is an error —
/// see the module docs.
pub fn render_table(rows: &[ContractDates]) -> Result<String, RenderError> {
    let mut sorted: Vec<&ContractDates> = rows.iter().collect();
    sorted.sort_by(|a, b| (a.root, a.year, a.month).cmp(&(b.root, b.year, b.month)));

    let mut seen: BTreeSet<(&str, String)> = BTreeSet::new();
    for row in &sorted {
        let key = (row.root, contract_month(row.year, row.month));
        if !seen.insert(key.clone()) {
            return Err(RenderError::DuplicateKey {
                root: key.0.to_string(),
                month: key.1,
            });
        }
        if spec_for(row.root).is_none() {
            return Err(RenderError::UnknownRoot {
                root: row.root.to_string(),
            });
        }
    }

    let mut s = String::new();
    s.push_str("// @generated by contract-calendar-gen. Do not edit.\n");
    s.push_str("// Futures contract close-out calendar.\n");
    s.push_str(
        "// (root, contract_month, settlement, last_trade_day, first_notice_day,\n\
         //  long_close_out, short_close_out), sorted by (root, contract_month).\n",
    );
    s.push_str(
        "//\n// IBKR force-liquidates an expiring position during a close-out period\n\
         // preceding expiry, WITHOUT additional notice. The deadline is NOT the\n\
         // expiry date:\n\
         //   long  = 2 business days before FIRST NOTICE DAY (physical) or last trade day\n\
         //   short = 2 business days before LAST TRADE DAY\n\
         // For a physically delivered contract First Notice Day is the last business\n\
         // day of the month PRECEDING delivery, so a December gold contract's long\n\
         // deadline falls in NOVEMBER — about a month before its expiry date.\n",
    );
    s.push_str(
        "//\n// Dates are YYYY-MM-DD; first_notice_day is \"\" for cash-settled\n\
         // contracts, which have none.\n",
    );
    s.push_str("#[allow(clippy::type_complexity)]\n");
    s.push_str(
        "pub static CONTRACT_CALENDAR_BAKED: &[(&str, &str, &str, &str, &str, &str, &str)] = &[\n",
    );

    for r in &sorted {
        let fnd = r
            .first_notice_day
            .map(|d| d.to_string())
            .unwrap_or_default();
        let settlement = spec_for(r.root)
            .map(|s| s.settlement)
            .unwrap_or(Settlement::Cash);
        s.push_str(&format!(
            "    ({:?}, {:?}, {:?}, {:?}, {:?}, {:?}, {:?}),\n",
            r.root,
            contract_month(r.year, r.month),
            settlement.as_str(),
            r.last_trade_day.to_string(),
            fnd,
            r.long_close_out.to_string(),
            r.short_close_out.to_string(),
        ));
    }
    s.push_str("];\n");
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules::{all_contract_dates, contract_dates, spec_for};

    fn gc_dec_2026() -> ContractDates {
        contract_dates(spec_for("GC").expect("GC known"), 2026, 12).expect("derivable")
    }

    #[test]
    fn renders_the_expected_columns() {
        let out = render_table(&[gc_dec_2026()]).expect("renders");
        assert!(out.contains("CONTRACT_CALENDAR_BAKED"));
        assert!(out.contains("@generated by contract-calendar-gen"));
        // root, month, settlement, last trade, FND, long, short.
        assert!(
            out.contains(
                r#"("GC", "202612", "physical", "2026-12-29", "2026-11-30", "2026-11-25", "2026-12-24")"#
            ),
            "unexpected row rendering:\n{out}"
        );
    }

    #[test]
    fn cash_settled_rows_have_an_empty_first_notice_day() {
        let es = contract_dates(spec_for("ES").expect("ES known"), 2026, 12).expect("derivable");
        let out = render_table(&[es]).expect("renders");
        assert!(out.contains(r#""cash", "2026-12-18", "", "#), "got:\n{out}");
    }

    #[test]
    fn duplicate_keys_are_rejected_not_silently_deduped() {
        // The coverage.rs / baked.rs mistake: a colliding key must not
        // silently resolve to the first row.
        let row = gc_dec_2026();
        let err = render_table(&[row.clone(), row]).expect_err("must reject");
        assert_eq!(
            err,
            RenderError::DuplicateKey {
                root: "GC".to_string(),
                month: "202612".to_string(),
            }
        );
    }

    #[test]
    fn rows_are_sorted_by_root_then_month() {
        let all = all_contract_dates(&[2026, 2027]);
        let out = render_table(&all).expect("renders");
        let es = out.find(r#"("ES","#).expect("ES present");
        let gc = out.find(r#"("GC","#).expect("GC present");
        let mes = out.find(r#"("MES","#).expect("MES present");
        assert!(es < gc && gc < mes, "roots must sort ES < GC < MES");
        // Within GC, months ascend.
        let feb = out.find(r#"("GC", "202602""#).expect("GC Feb 2026");
        let dec = out.find(r#"("GC", "202612""#).expect("GC Dec 2026");
        assert!(feb < dec, "months must ascend within a root");
    }

    #[test]
    fn contract_month_is_zero_padded() {
        assert_eq!(contract_month(2026, 9), "202609");
        assert_eq!(contract_month(2026, 12), "202612");
    }

    #[test]
    fn the_generated_table_parses_as_it_will_be_read() {
        // Guard the shape the `core` lookup depends on: seven string columns
        // per row. A column added here without updating `core` would silently
        // shift every field.
        let out = render_table(&all_contract_dates(&[2026])).expect("renders");
        let row = out
            .lines()
            .find(|l| l.trim_start().starts_with(r#"("GC","#))
            .expect("a GC row");
        assert_eq!(
            row.matches('"').count(),
            14,
            "seven quoted columns expected, got: {row}"
        );
    }
}
