//! System 1 of the DST-aware spread blackout: reject a brand-new entry
//! that fires during the post-NY-close liquidity trough when the live
//! spread on the incoming instrument is elevated. Reject, not delay — the
//! next signal bar refires and re-checks (by then the spread may have
//! recovered).
//!
//! This is the **pure decision** (KV-free, broker-free, wasm-safe), so it
//! lives in `core` and is shared by BOTH consumers
//! (`[[strategy_changes_in_both_replayer_and_worker]]`):
//!
//! - the **live worker** wraps it with a KV window read + a live broker
//!   quote sample (`run_enter`, `src/lib.rs`);
//! - the **offline replay** wraps it with the fire-bar `ask_c − bid_c`
//!   spread from the recorded candle and an `is_ny_close_edge` stand-in for
//!   the window marker (`engine::simulate_fill`).
//!
//! Keeping the decision + the baked per-instrument baseline here is what
//! lets a replay 422 exactly the entries the live worker would 423.

/// Decide whether to reject an entry on spread-blackout grounds.
///
/// `window_open`  — the global `spread-blackout:window` marker is present
///                  (Sub-plan 2). When `false` we never sample the spread.
/// `spread_pips`  — live `ask − bid` for the incoming instrument, in pips.
/// `threshold_pips` — the "elevated" cutoff (see OPEN QUESTION on
///                  [`elevated_threshold_pips`]).
///
/// Returns `true` ⇒ REJECT (`rejected: spread-blackout`).
/// `false` ⇒ fall through to the normal entry (window closed, OR window
/// open but the spread is fine — that instrument/day is not blacked out).
///
/// Strictly `>`: a spread exactly at the threshold is allowed (the
/// boundary is deliberately permissive — see the boundary unit test).
pub fn spread_blackout_decision(window_open: bool, spread_pips: f64, threshold_pips: f64) -> bool {
    window_open && spread_pips > threshold_pips
}

/// The compile-time per-instrument spread baseline, generated by
/// `core/build.rs` from the `spread-sampler-cron` YAML samples. Each row is
/// `(tradenation_market_name, low_pips, high_pips, median_pips, n)`,
/// sorted by name. Empty when no samples are checked out (→ flat fallback).
///
/// **Being retired.** The spread-HOUR mask now comes from the candle-derived
/// [`baseline_candle`] table (see `baked_candle_mask`); the sampler table still
/// backs the pip *baseline* stats (`baked_baseline` → `elevated_threshold_pips`
/// / operator message) and the System-2 *widen* (`baked_spread_hours`) until
/// those migrate to the candle table too. See
/// `SCOPING-candle-derived-spread-baseline.md`.
mod baseline {
    include!(concat!(env!("OUT_DIR"), "/spread_baseline.rs"));
}

/// The candle-derived, **per-broker** spread-hour table produced offline by the
/// `spread-baseline-gen` binary and committed as a source file (not build-time
/// generated — the fetch is a network op). Each row is
/// `(broker, symbol, reviewed, elevated_hours_mask, hour_widen_frac[24])`,
/// sorted by `(broker, symbol)`.
///
/// This is the source of truth for **which UTC hours are spread hours**
/// (`is_spread_hour`). It supersedes the sampler mask, which over-flagged tight
/// crosses' whole overnight block (the "12pm Brisbane rubbish" bug). The
/// per-broker keying means OANDA `EUR_USD` and TradeNation `EUR/USD` carry their
/// own masks — no canonical sharing. Symbol strings never collide across
/// brokers, so the lookup keys on the symbol alone.
mod baseline_candle {
    include!("spread_baseline_candle.rs");
}

/// The candle-derived spread-hour **mask** for `instrument`, or `None` when it
/// isn't in the candle table. Keyed on the broker symbol string (the same
/// `resolved.instrument` the gate passes); symbols are unique across brokers,
/// so the `broker` column is not needed to disambiguate the lookup.
///
/// The table is sorted by `(broker, symbol)`, NOT by `symbol` alone, so a plain
/// `binary_search` on the symbol would be wrong — we scan for an exact symbol
/// match. The table is small (~200 rows) and this is called per-tick per-plan,
/// which is cheap; a symbol-sorted index can be added if it ever matters.
fn baked_candle_mask(instrument: &str) -> Option<u32> {
    baseline_candle::SPREAD_BASELINE_CANDLE
        .iter()
        .find(|(_broker, symbol, ..)| *symbol == instrument)
        .map(|(.., _reviewed, mask, _widen)| *mask)
}

/// The reject line, as a multiple of an instrument's *normal* (median)
/// spread. The 2026-06-23 spread-hour data showed the post-NY-close
/// blowout is an **FX** phenomenon — FX crosses spike 10–20× their normal
/// (AUD/USD 0.4p → 6p, EUR/GBP 0.5p → 10p), while commodities/indices
/// (Copper, Gold) stay flat. So a per-instrument multiple of normal is the
/// right shape: 5× sits clearly above resting jitter and busy-news
/// widening, yet well below a real spread-hour spike (which is ≥10×), so it
/// catches the blowout. For a flat-spread instrument like Copper (normal
/// ~150p) the line is ~750p — never a false block.
///
/// Chosen over "observed max" because with a short sample window a quiet
/// instrument's max can equal its normal, which would re-introduce the
/// over-blocking this whole change fixed.
pub const SPREAD_REJECT_MULTIPLE: f64 = 5.0;

/// "Elevated" spread cutoff in pips for System 1's reject, per instrument.
///
/// Looks the instrument up in the baked baseline (keyed by the
/// broker-canonical TradeNation name — the same `resolved.instrument` the
/// gate passes). When found, the threshold is
/// `median × SPREAD_REJECT_MULTIPLE` (5× the instrument's own normal
/// spread) — see [`SPREAD_REJECT_MULTIPLE`].
///
/// Falls back to the flat [`SPREAD_BLACKOUT_ELEVATED_PIPS`] for any
/// instrument not in the baseline (a fresh asset, or one whose samples
/// lacked a pip size). Re-baked whenever the committed samples grow.
pub fn elevated_threshold_pips(instrument: &str) -> f64 {
    match baked_baseline(instrument) {
        Some((_low, _high, median)) => median * SPREAD_REJECT_MULTIPLE,
        None => SPREAD_BLACKOUT_ELEVATED_PIPS,
    }
}

/// The baked `(low, high, median)` pips for an instrument, or `None` when
/// it isn't in the baseline. Exposed so the reject path can name the
/// instrument's normal vs. current spread in the operator-facing message.
pub fn baked_baseline(instrument: &str) -> Option<(f64, f64, f64)> {
    baseline::SPREAD_BASELINE
        .binary_search_by(|(name, ..)| name.cmp(&instrument))
        .ok()
        .map(|i| {
            let (_, low, high, median, ..) = baseline::SPREAD_BASELINE[i];
            (low, high, median)
        })
}

/// The baked `(elevated_hours_mask, hour_widen_pips)` for an instrument, or
/// `None` when it isn't in the baseline. The mask's bit `h` = UTC hour `h`
/// is a learned spread hour; `hour_widen_pips[h]` is that hour's p90 widen
/// size (0.0 when not elevated). See `core/build.rs::spread_hours`.
fn baked_spread_hours(instrument: &str) -> Option<(u32, [f64; 24])> {
    baseline::SPREAD_BASELINE
        .binary_search_by(|(name, ..)| name.cmp(&instrument))
        .ok()
        .map(|i| {
            let (.., mask, widen) = baseline::SPREAD_BASELINE[i];
            (mask, widen)
        })
}

/// How many minutes ahead of an elevated hour's start we pre-emptively
/// widen an open stop. The spread spike is at the top of the hour; widening
/// ~30 min early means the stop is already out of the way before the spike
/// lands, rather than racing it. Shared constant so the worker cron and the
/// offline replay lead by the same amount.
pub const SPREAD_HOUR_LEAD_MINUTES: i64 = 30;

/// The pre-emptive widen size (in pips) for `instrument` at `now`, or `None`
/// when `now` is **not** in (or within [`SPREAD_HOUR_LEAD_MINUTES`] of the
/// start of) one of this instrument's learned spread hours.
///
/// Timing is entirely from baked history — no live spread read is needed to
/// decide *when* or *how much* to widen (the caller may still floor the
/// result by the live spread; see the System-2 consumer). The returned pips
/// is the elevated hour's baked p90.
///
/// Lead handling: if `now` is within the lead window of the *next* UTC hour
/// and that next hour is elevated, we return the next hour's widen (so the
/// stop is out of the way before the spike). Otherwise we return the current
/// hour's widen iff the current hour is elevated.
///
/// `None` for an instrument absent from the baseline, or one whose samples
/// yielded no learnable spread hours (mask 0) — the caller falls back to the
/// legacy [`is_ny_close_edge`](crate::ny_clock::is_ny_close_edge) gate for
/// those, so nothing regresses for un-sampled assets.
pub fn spread_hour_widen_pips(instrument: &str, now: chrono::DateTime<chrono::Utc>) -> Option<f64> {
    let (mask, widen) = baked_spread_hours(instrument)?;
    spread_hour_widen_for(mask, &widen, now)
}

/// Pure spread-hour-widen decision over an explicit `(mask, widen)` — the
/// unit-testable seam behind [`spread_hour_widen_pips`], free of the baked
/// table so tests can drive it with synthetic instrument shapes.
///
/// Returns the widen pips iff `now`'s hour is elevated, or `now` is within
/// [`SPREAD_HOUR_LEAD_MINUTES`] of the top of a next hour that is elevated
/// (look-ahead, so the stop is out of the way before the spike). `None`
/// otherwise (including a mask of 0).
fn spread_hour_widen_for(
    mask: u32,
    widen: &[f64; 24],
    now: chrono::DateTime<chrono::Utc>,
) -> Option<f64> {
    use chrono::Timelike;
    if mask == 0 {
        return None;
    }
    let hour = now.hour() as usize;
    // Within the lead window of the next hour's top? Then look ahead.
    let minutes_into_hour = now.minute() as i64;
    let lead_reaches_next = 60 - minutes_into_hour <= SPREAD_HOUR_LEAD_MINUTES;
    if lead_reaches_next {
        let next = (hour + 1) % 24;
        if mask & (1 << next) != 0 {
            return Some(widen[next]);
        }
    }
    if mask & (1 << hour) != 0 {
        return Some(widen[hour]);
    }
    None
}

/// Is `now` a spread hour for `instrument` (per-instrument, learned)?
///
/// The hour membership comes from the **candle-derived** mask
/// ([`baked_candle_mask`]) — the source of truth that fixed the sampler's
/// whole-overnight over-flag. The same [`SPREAD_HOUR_LEAD_MINUTES`] look-ahead
/// as the System-2 widen applies (so System 3 cancels a resting order 30 min
/// before the spike, matching the widen lead).
///
/// Fallbacks preserve prior behaviour for anything the candle table doesn't
/// cover: an instrument absent from the candle table, or present with an empty
/// mask, drops to the legacy NY-close-edge gate. (An empty candle mask can mean
/// "reviewed, genuinely flat" — for those the NY-close-edge fallback is the
/// same conservative default the sampler gave an un-learned instrument; a later
/// stage can honour the explicit `reviewed` verdict to skip the fallback.)
pub fn is_spread_hour(instrument: &str, now: chrono::DateTime<chrono::Utc>) -> bool {
    match baked_candle_mask(instrument) {
        Some(mask) if mask != 0 => mask_active_with_lead(mask, now),
        // Absent, or reviewed-flat (mask 0) → legacy fallback.
        _ => crate::ny_clock::is_ny_close_edge(now),
    }
}

/// Is `mask` active at `now`, honouring the [`SPREAD_HOUR_LEAD_MINUTES`]
/// look-ahead? The mask-only twin of [`spread_hour_widen_for`] (which returns
/// the widen size); this returns just the boolean membership so `is_spread_hour`
/// can key off the candle mask without a widen array. Kept structurally
/// identical to `spread_hour_widen_for` so the two never drift.
fn mask_active_with_lead(mask: u32, now: chrono::DateTime<chrono::Utc>) -> bool {
    use chrono::Timelike;
    if mask == 0 {
        return false;
    }
    let hour = now.hour() as usize;
    let minutes_into_hour = now.minute() as i64;
    let lead_reaches_next = 60 - minutes_into_hour <= SPREAD_HOUR_LEAD_MINUTES;
    if lead_reaches_next {
        let next = (hour + 1) % 24;
        if mask & (1 << next) != 0 {
            return true;
        }
    }
    mask & (1 << hour) != 0
}

/// Placeholder cutoff. A thin FX cross normally spreads ~2p and blows to
/// ~20p+ in the trough; 8p sits clearly above normal and below the
/// blowout. Majors (EUR/USD ~1p) never trip it, so the window is
/// self-scoping. Calibrate on demo before relying on it.
///
/// Provisional — see [`elevated_threshold_pips`] for the open question and
/// the hysteresis relationship to [`SPREAD_BLACKOUT_RECOVERED_PIPS`].
pub const SPREAD_BLACKOUT_ELEVATED_PIPS: f64 = 8.0;

/// "Recovered" spread cutoff in pips for the Sub-plan-2 recovery watcher
/// (`src/cron/blackout_watch.rs`). The spread is considered back to normal
/// once the sampled `ask − bid` (in pips) drops to/under this.
///
/// **Hysteresis (single tuning point):** lives here, beside the *elevated*
/// cutoff, so the two are tuned together and the invariant
/// `RECOVERED < ELEVATED` is visible in one file. Recovered sits **below**
/// elevated so the window doesn't flap right at the boundary: an entry is
/// blacked out above 8p, and the watcher only declares recovery once the
/// spread has fallen all the way back to ≤4p. Both are provisional and
/// MUST be calibrated together on demo — see [`elevated_threshold_pips`].
pub const SPREAD_BLACKOUT_RECOVERED_PIPS: f64 = 4.0;

/// The spread-blackout backstop's two concerns, split (2026-07).
///
/// Historically a single `BLACKOUT_BACKSTOP_SECONDS = 3h` drove BOTH the
/// per-trade record's TTL and the "force-restore a stuck record" safety
/// ceiling. That conflation broke for **multi-hour** learned blocks: AUD/CHF's
/// baked block is 21:00–05:00Z (8h), but the record expired at 21:00 + 3h =
/// 00:00Z — mid-block, *before* the block-lift restore at 05:00Z could find it —
/// so the cancelled order was never restored (0R instead of the intended
/// deferred fill). And the 3h backstop *itself* would fire at 00:00Z, force-
/// restoring the order back INTO the still-active trough. The two roles want
/// opposite sizing, so they're now separate:
///
/// 1. **Record TTL = the block's own length + grace** ([`spread_block_ttl_seconds`]).
///    The cancel-record must always OUTLIVE its own spread-hour block so the
///    normal OFF-side restore (block-lifted / spread-recovered) can still find it.
///    Per-instrument, derived from the baked mask.
/// 2. **Safety force-restore ceiling** ([`SAFETY_FORCE_RESTORE_SECONDS`]) — a
///    tight, global last-resort for a record that is somehow still `applied` long
///    after it should have cleared. Gated so it NEVER fires while the instrument
///    is still in a spread hour (see `backstop_due` call sites), so it can't
///    restore into an active block.
///
/// The normal block-lift restore should almost always win first (TTL ≥ block);
/// the safety ceiling is belt-and-braces.
///
/// Sized as a genuine LAST-RESORT: **longer than any realistic learned block** so
/// it fires only when the normal `off_now` restore has somehow failed to clear a
/// record for far longer than a legitimate block (e.g. a persistent quote-error
/// storm, or a repeatedly-failing `clear`). At 12h it sits comfortably past the
/// widest overnight FX block (~8h) yet well under a full day; combined with the
/// `!is_spread_hour` gate on its call site, it can never restore into an active
/// block even for a mis-baked over-long mask. (The old 3h value was BOTH the
/// per-record TTL and this ceiling — a conflation that expired an 8h AUD/CHF
/// record at 3h, before its block-lift restore. TTL is now [`spread_block_ttl_seconds`].)
///
/// Lives in `core` (not the cron crate) so the offline replay computes the same
/// values as the live recovery watcher without depending on `trade-control-cron`.
/// The cron crate re-exports both.
pub const SAFETY_FORCE_RESTORE_SECONDS: u64 = 12 * 60 * 60;

/// Grace tail added to a block's own length when sizing a cancel-record's TTL,
/// so the record comfortably outlives the block-lift restore (which fires the
/// tick the block ends). One extra hour: enough slack for the OFF-side pass to
/// run at/after the lift without the record having lapsed.
pub const SPREAD_BLOCK_TTL_GRACE_SECONDS: u64 = 60 * 60;

/// Hard ceiling on a walked block length (defensive): no learned block should
/// span the whole day, but if a (buggy) mask were all-ones we must not loop 24×
/// and hand back a 24h TTL. Caps the walk at 23 hours.
const MAX_BLOCK_HOURS: u32 = 23;

/// The TTL (seconds) a spread-hour cancel-record should carry so it OUTLIVES its
/// own block: the length of the contiguous spread-hour run that `opened_at` sits
/// in, plus [`SPREAD_BLOCK_TTL_GRACE_SECONDS`].
///
/// Walks forward hour-by-hour from `opened_at` through
/// [`is_spread_hour`] until the first non-spread hour (wrap-around midnight is
/// handled by [`is_spread_hour`]'s hour-of-day mask). A record opened at the very
/// top of the block gets `block_len + grace`; one opened partway through gets the
/// *remaining* block + grace, which is still ≥ the time to the lift (all we need:
/// the record must live until the lift). Falls back to `grace` alone when
/// `opened_at` is somehow not itself a spread hour (nothing to outlive), and is
/// capped at [`MAX_BLOCK_HOURS`] + grace for a pathological all-hours mask.
pub fn spread_block_ttl_seconds(instrument: &str, opened_at: chrono::DateTime<chrono::Utc>) -> u64 {
    use chrono::Timelike;
    // Walk on the pure per-instrument hour mask when the instrument has one
    // (deterministic block edges); fall back to a real-clock probe through
    // `is_spread_hour` for legacy NY-close-edge instruments (no baked mask).
    let hours = match baked_spread_hours(instrument) {
        Some((mask, _)) if mask != 0 => block_hours_from_mask(mask, opened_at.hour()),
        _ => block_hours_by_probe(instrument, opened_at),
    };
    hours as u64 * 3600 + SPREAD_BLOCK_TTL_GRACE_SECONDS
}

/// The number of consecutive elevated hours in `mask` starting at (and
/// including) `opened_hour`, wrapping around midnight, capped at
/// [`MAX_BLOCK_HOURS`]. `0` when `opened_hour` itself isn't elevated (nothing to
/// outlive). Pure over the 24-bit mask so it's testable with synthetic shapes.
fn block_hours_from_mask(mask: u32, opened_hour: u32) -> u32 {
    let mut hours: u32 = 0;
    while hours < MAX_BLOCK_HOURS {
        let h = (opened_hour + hours) % 24;
        if mask & (1 << h) == 0 {
            break;
        }
        hours += 1;
    }
    hours
}

/// Real-clock fallback for legacy (no-mask) instruments: probe `is_spread_hour`
/// forward hour-by-hour from `opened_at`.
fn block_hours_by_probe(instrument: &str, opened_at: chrono::DateTime<chrono::Utc>) -> u32 {
    let mut hours: u32 = 0;
    while hours < MAX_BLOCK_HOURS {
        let probe = opened_at + chrono::Duration::hours(hours as i64);
        if !is_spread_hour(instrument, probe) {
            break;
        }
        hours += 1;
    }
    hours
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn window_closed_never_rejects() {
        // Window closed ⇒ pass even with an absurdly wide spread, and the
        // wrapper never calls `get_quote` on this branch.
        assert!(!spread_blackout_decision(false, 50.0, 8.0));
    }

    #[test]
    fn window_open_wide_spread_rejects() {
        assert!(spread_blackout_decision(true, 20.0, 8.0));
    }

    #[test]
    fn window_open_tight_spread_passes() {
        assert!(!spread_blackout_decision(true, 2.0, 8.0));
    }

    #[test]
    fn boundary_exactly_at_threshold_passes() {
        // Strictly `>`, so exactly-at-threshold falls through (allowed).
        assert!(!spread_blackout_decision(true, 8.0, 8.0));
    }

    #[test]
    #[allow(clippy::assertions_on_constants)]
    fn recovered_cutoff_sits_below_elevated_for_hysteresis() {
        // The window must not flap at the boundary: recovery is only
        // declared once the spread has fallen below the (lower) recovered
        // cutoff, not the moment it dips under the elevated one. Constant
        // assertion on purpose — it guards the tuning invariant if a future
        // edit to either const inverts the pair.
        assert!(SPREAD_BLACKOUT_RECOVERED_PIPS < SPREAD_BLACKOUT_ELEVATED_PIPS);
    }

    #[test]
    fn unknown_instrument_falls_back_to_flat_constant() {
        // A made-up name can't be in the baked baseline → flat fallback.
        assert_eq!(
            elevated_threshold_pips("DEFINITELY NOT A REAL MARKET ZZZ"),
            SPREAD_BLACKOUT_ELEVATED_PIPS
        );
        assert_eq!(elevated_threshold_pips(""), SPREAD_BLACKOUT_ELEVATED_PIPS);
    }

    #[test]
    fn baked_baseline_is_sorted_and_self_consistent() {
        // The generated table must be sorted by name (binary_search relies
        // on it) and every row must satisfy low <= median <= high.
        let mut prev: Option<&str> = None;
        for (name, low, high, median, n, mask, widen) in baseline::SPREAD_BASELINE {
            if let Some(p) = prev {
                assert!(p < *name, "baseline not sorted: {p:?} !< {name:?}");
            }
            prev = Some(name);
            assert!(*n > 0, "{name}: zero samples");
            assert!(
                *low <= *median && *median <= *high,
                "{name}: low {low} median {median} high {high} not ordered",
            );
            // Mask/widen coherence: an elevated hour must carry a positive
            // widen, and a non-elevated hour must bake 0.0 (nothing to widen
            // by). This guards the build.rs render against drift.
            for h in 0..24 {
                let elevated = mask & (1 << h) != 0;
                let w = widen[h];
                if elevated {
                    assert!(w > 0.0, "{name}: hour {h} elevated but widen {w} <= 0");
                } else {
                    assert!(w == 0.0, "{name}: hour {h} not elevated but widen {w} != 0");
                }
            }
        }
    }

    #[test]
    fn baked_threshold_is_five_times_normal() {
        // For every baked instrument the threshold is exactly 5x its
        // median normal spread — high enough to pass resting/busy-news
        // widening, low enough to reject a ≥10x spread-hour blowout.
        for (name, _low, _high, median, ..) in baseline::SPREAD_BASELINE {
            let t = elevated_threshold_pips(name);
            assert!(
                (t - median * SPREAD_REJECT_MULTIPLE).abs() < 1e-9,
                "{name}: threshold {t} != 5x median {median}",
            );
        }
    }

    // --- spread-hour widen lookup (pure seam, synthetic tables) ---

    use chrono::{DateTime, Utc};

    fn ts(s: &str) -> DateTime<Utc> {
        s.parse().expect("valid rfc3339 fixture")
    }

    /// A EUR/USD-shaped mask: a single spike hour (21:00 UTC), widen 5p.
    fn eurusd_shape() -> (u32, [f64; 24]) {
        let mut w = [0.0; 24];
        w[21] = 5.0;
        (1 << 21, w)
    }

    /// A Gold-shaped mask: a structural overnight block (18:00–06:00 UTC),
    /// widen 75p across the block.
    fn gold_shape() -> (u32, [f64; 24]) {
        let mut mask = 0u32;
        let mut w = [0.0; 24];
        for h in (18..24).chain(0..7) {
            mask |= 1 << h;
            w[h] = 75.0;
        }
        (mask, w)
    }

    #[test]
    fn widen_fires_inside_the_elevated_hour() {
        let (m, w) = eurusd_shape();
        // 21:15 UTC — squarely inside the elevated hour.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T21:15:00Z")),
            Some(5.0),
        );
    }

    #[test]
    fn widen_none_outside_any_elevated_hour() {
        let (m, w) = eurusd_shape();
        // Midday, nowhere near 21:00.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T12:00:00Z")),
            None
        );
    }

    #[test]
    fn widen_leads_into_the_next_elevated_hour() {
        let (m, w) = eurusd_shape();
        // 20:35 UTC — 25 min before 21:00, inside the 30-min lead → widen now.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T20:35:00Z")),
            Some(5.0),
        );
        // 20:29 UTC — 31 min before, just outside the lead → not yet.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T20:29:00Z")),
            None
        );
    }

    #[test]
    fn widen_lead_wraps_across_midnight() {
        // Gold's block includes hour 0. At 23:40 UTC the next hour (0) is
        // elevated and within the lead → widen, exercising the (h+1)%24 wrap.
        let (m, w) = gold_shape();
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T23:40:00Z")),
            Some(75.0),
        );
    }

    #[test]
    fn widen_covers_a_structural_overnight_block() {
        let (m, w) = gold_shape();
        // Deep in the overnight block.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T02:00:00Z")),
            Some(75.0),
        );
        // Daytime, block is closed.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T12:00:00Z")),
            None
        );
    }

    #[test]
    fn widen_empty_mask_never_fires() {
        // A flat-fat-tail instrument bakes mask 0 → never a spread hour.
        assert_eq!(
            spread_hour_widen_for(0, &[0.0; 24], ts("2026-07-01T21:15:00Z")),
            None
        );
    }

    #[test]
    fn is_spread_hour_unknown_instrument_falls_back_to_ny_close() {
        // No baseline row → fall back to the legacy NY-close-edge gate.
        // 12-Mar-2026 is EDT, close edge 21:00 UTC.
        assert!(is_spread_hour(
            "DEFINITELY NOT A REAL MARKET ZZZ",
            ts("2026-03-12T21:00:00Z")
        ));
        // A non-edge hour on the same (unknown) instrument → false.
        assert!(!is_spread_hour(
            "DEFINITELY NOT A REAL MARKET ZZZ",
            ts("2026-03-12T10:00:00Z")
        ));
    }

    // --- Golden origin-case anchor (PR 0, shared-pending-lifecycle) ---
    //
    // These pin the ON-trigger for the case that motivated the whole
    // shared-lifecycle work: the AUD/CHF 2026-07-08T21:00Z fill-into-the-
    // spread-hour −2R (SCOPING-spread-hour-rubbish-candle.md). They assert the
    // *invariant* — "is 21:00Z a baked spread hour for AUD/CHF, and does its
    // widen ≈ the 12p gap we observed" — NOT the raw mask int, which is
    // data-derived and drifts as `spread-sampler-cron` accrues samples. When
    // PR 2 flips the live cancel trigger from a live-quote sample to this baked
    // predicate, this is the regression baseline that must stay green.

    /// The exact origin bar (07:00 Brisbane = 21:00 UTC, 2026-07-08) is a baked
    /// spread hour for AUD/CHF, and its baked widen is the ~12p blowout that
    /// straddled the entry/SL bracket. This is the ON-trigger the shared
    /// lifecycle keys off — no live quote.
    #[test]
    fn aud_chf_origin_bar_is_a_baked_spread_hour() {
        let origin = ts("2026-07-08T21:00:00Z");
        assert!(
            is_spread_hour("AUD/CHF", origin),
            "AUD/CHF 21:00Z (the −2R origin bar) must read as a baked spread hour"
        );
        // Widen at that hour is the p90 blowout — ~12p (the observed spread gap
        // that straddled entry 0.55980 / SL 0.56070). Assert it is a real
        // blowout (>= 10p), tolerant of sample-driven drift in the exact value.
        let widen =
            spread_hour_widen_pips("AUD/CHF", origin).expect("origin bar must carry a baked widen");
        assert!(
            widen >= 10.0,
            "AUD/CHF 21:00Z widen {widen} must be a >=10p blowout (observed ~12p)"
        );
    }

    /// The 30-min lead applies to the origin case too: 20:35 UTC (25 min before
    /// the 21:00Z spike) already reads as a spread hour, so a resting order is
    /// removed *before* the blowout lands, not racing it.
    #[test]
    fn aud_chf_origin_bar_lead_window_is_a_spread_hour() {
        assert!(
            is_spread_hour("AUD/CHF", ts("2026-07-08T20:35:00Z")),
            "25 min before the 21:00Z spike is inside the 30-min lead → spread hour"
        );
        assert!(
            !is_spread_hour("AUD/CHF", ts("2026-07-08T20:25:00Z")),
            "35 min before is outside the lead → not yet a spread hour"
        );
    }

    /// A clean AUD/CHF hour (well away from the overnight/NY-close blocks) is
    /// NOT a spread hour — the predicate-false side of the origin anchor, so a
    /// removed order restores on such a bar. 12:00 UTC is midday London,
    /// squarely outside AUD/CHF's baked blocks.
    #[test]
    fn aud_chf_midday_is_not_a_spread_hour() {
        assert!(
            !is_spread_hour("AUD/CHF", ts("2026-07-08T12:00:00Z")),
            "midday is a clean bar → an order removed at 21:00Z restores here"
        );
    }

    /// Regression for the GBP/AUD QM bug: the old sampler mask flagged GBP/AUD's
    /// whole overnight block (UTC [0-5,21,22,23] = Brisbane 07:00-15:00), so a
    /// 10am golden Pinbar confirming at 12pm (UTC ~02:00) had its confirmation
    /// bar suppressed and the QM leg never entered. The candle-derived mask is
    /// [21] only, so the daytime block is NO LONGER a spread hour — the
    /// confirmation fires and the entry can go in.
    #[test]
    fn gbp_aud_daytime_is_not_a_spread_hour_candle_mask() {
        // TradeNation GBP/AUD candle mask is [21] only.
        // 02:00 UTC (Brisbane 12:00, the confirmation bar) must be CLEAN now.
        assert!(
            !is_spread_hour("GBP/AUD", ts("2026-07-08T02:00:00Z")),
            "GBP/AUD 02:00Z (Bris 12:00, the QM confirmation bar) must NOT be a \
             spread hour under the candle mask (was wrongly flagged by the sampler)"
        );
        // The genuine 21:00Z NY-close spike is still a spread hour.
        assert!(
            is_spread_hour("GBP/AUD", ts("2026-07-08T21:00:00Z")),
            "GBP/AUD 21:00Z (the genuine NY-close spike) is still a spread hour"
        );
        // The rest of the old wrongly-flagged block is clean: 03:00Z (Bris 13:00).
        assert!(
            !is_spread_hour("GBP/AUD", ts("2026-07-08T03:00:00Z")),
            "GBP/AUD 03:00Z (Bris 13:00) must NOT be a spread hour"
        );
    }

    // --- block-length TTL (concern 1 of the backstop split) ---

    /// A contiguous 8h block (bits 21..=23 + 0..=4, AUD/CHF-shaped) opened at its
    /// top (hour 21) spans all 8 hours.
    #[test]
    fn block_hours_multi_hour_wrap_from_top() {
        // 21,22,23,0,1,2,3,4 set.
        let mask: u32 = (1 << 21)
            | (1 << 22)
            | (1 << 23)
            | (1 << 0)
            | (1 << 1)
            | (1 << 2)
            | (1 << 3)
            | (1 << 4);
        assert_eq!(block_hours_from_mask(mask, 21), 8);
    }

    /// Opened partway through the same 8h block (hour 0) → the REMAINING block
    /// (0,1,2,3,4 = 5h). Still ≥ the time to the lift, which is all the TTL needs.
    #[test]
    fn block_hours_multi_hour_wrap_from_middle() {
        let mask: u32 = (1 << 21)
            | (1 << 22)
            | (1 << 23)
            | (1 << 0)
            | (1 << 1)
            | (1 << 2)
            | (1 << 3)
            | (1 << 4);
        assert_eq!(block_hours_from_mask(mask, 0), 5);
    }

    /// A single elevated hour (majors-shaped, just 21:00Z) → a 1h block.
    #[test]
    fn block_hours_single_hour() {
        assert_eq!(block_hours_from_mask(1 << 21, 21), 1);
    }

    /// Opening on a non-elevated hour → 0 (nothing to outlive); the TTL is then
    /// just the grace.
    #[test]
    fn block_hours_zero_off_block() {
        assert_eq!(block_hours_from_mask(1 << 21, 12), 0);
    }

    /// A degenerate all-ones mask is capped at MAX_BLOCK_HOURS (never 24) so the
    /// TTL can't blow out to a full day.
    #[test]
    fn block_hours_all_ones_is_capped() {
        assert_eq!(block_hours_from_mask(u32::MAX, 0), MAX_BLOCK_HOURS);
    }

    /// The public seconds helper: block hours × 3600 + grace.
    #[test]
    fn ttl_seconds_adds_grace() {
        // 1h block + 1h grace = 2h. Use the pure mask helper's math directly so
        // the assertion doesn't depend on the baked table.
        let hours = block_hours_from_mask(1 << 21, 21);
        let ttl = hours as u64 * 3600 + SPREAD_BLOCK_TTL_GRACE_SECONDS;
        assert_eq!(ttl, 2 * 3600);
    }

    /// AUD/CHF's baked block, opened at 21:00Z, must yield a TTL that OUTLIVES the
    /// block AND exceeds the 3h that used to expire it prematurely — the whole
    /// point of the split. (Uses the baked table via the public helper.)
    #[test]
    fn aud_chf_block_ttl_outlives_the_block_and_beats_the_old_3h() {
        let ttl = spread_block_ttl_seconds("AUD/CHF", ts("2026-07-08T21:00:00Z"));
        assert!(
            ttl > 3 * 3600,
            "AUD/CHF block TTL must exceed the old 3h that expired the record mid-block, got {ttl}s"
        );
        // Sanity: a multi-hour block + 1h grace lands well above 3h and below a day.
        assert!(
            ttl < 24 * 3600,
            "TTL must not blow out to a full day, got {ttl}s"
        );
    }
}
