//! System 1 of the DST-aware spread blackout: reject a brand-new entry
//! that fires during the post-NY-close liquidity trough when the live
//! spread on the incoming instrument is elevated. Reject, not delay — the
//! next signal bar refires and re-checks (by then the spread may have
//! recovered).
//!
//! This is the **pure decision** (KV-free, broker-free, wasm-safe), so it
//! lives in `core` and is shared by BOTH consumers
//! (`[[strategy_changes_in_both_replayer_and_worker]]`):
//!
//! - the **live worker** wraps it with a KV window read + a live broker
//!   quote sample (`run_enter`, `src/lib.rs`);
//! - the **offline replay** wraps it with the fire-bar `ask_c − bid_c`
//!   spread from the recorded candle and an `is_ny_close_edge` stand-in for
//!   the window marker (`engine::simulate_fill`).
//!
//! Keeping the decision + the baked per-instrument baseline here is what
//! lets a replay 422 exactly the entries the live worker would 423.

/// Decide whether to reject an entry on spread-blackout grounds.
///
/// `window_open`  — the global `spread-blackout:window` marker is present
///                  (Sub-plan 2). When `false` we never sample the spread.
/// `spread_pips`  — live `ask − bid` for the incoming instrument, in pips.
/// `threshold_pips` — the "elevated" cutoff (see OPEN QUESTION on
///                  [`elevated_threshold_pips`]).
///
/// Returns `true` ⇒ REJECT (`rejected: spread-blackout`).
/// `false` ⇒ fall through to the normal entry (window closed, OR window
/// open but the spread is fine — that instrument/day is not blacked out).
///
/// Strictly `>`: a spread exactly at the threshold is allowed (the
/// boundary is deliberately permissive — see the boundary unit test).
pub fn spread_blackout_decision(window_open: bool, spread_pips: f64, threshold_pips: f64) -> bool {
    window_open && spread_pips > threshold_pips
}

/// The compile-time per-instrument spread baseline, generated by
/// `core/build.rs` from the `spread-sampler-cron` YAML samples. Each row is
/// `(tradenation_market_name, low_pips, high_pips, median_pips, n)`,
/// sorted by name. Empty when no samples are checked out (→ flat fallback).
mod baseline {
    include!(concat!(env!("OUT_DIR"), "/spread_baseline.rs"));
}

/// The reject line, as a multiple of an instrument's *normal* (median)
/// spread. The 2026-06-23 spread-hour data showed the post-NY-close
/// blowout is an **FX** phenomenon — FX crosses spike 10–20× their normal
/// (AUD/USD 0.4p → 6p, EUR/GBP 0.5p → 10p), while commodities/indices
/// (Copper, Gold) stay flat. So a per-instrument multiple of normal is the
/// right shape: 5× sits clearly above resting jitter and busy-news
/// widening, yet well below a real spread-hour spike (which is ≥10×), so it
/// catches the blowout. For a flat-spread instrument like Copper (normal
/// ~150p) the line is ~750p — never a false block.
///
/// Chosen over "observed max" because with a short sample window a quiet
/// instrument's max can equal its normal, which would re-introduce the
/// over-blocking this whole change fixed.
pub const SPREAD_REJECT_MULTIPLE: f64 = 5.0;

/// "Elevated" spread cutoff in pips for System 1's reject, per instrument.
///
/// Looks the instrument up in the baked baseline (keyed by the
/// broker-canonical TradeNation name — the same `resolved.instrument` the
/// gate passes). When found, the threshold is
/// `median × SPREAD_REJECT_MULTIPLE` (5× the instrument's own normal
/// spread) — see [`SPREAD_REJECT_MULTIPLE`].
///
/// Falls back to the flat [`SPREAD_BLACKOUT_ELEVATED_PIPS`] for any
/// instrument not in the baseline (a fresh asset, or one whose samples
/// lacked a pip size). Re-baked whenever the committed samples grow.
pub fn elevated_threshold_pips(instrument: &str) -> f64 {
    match baked_baseline(instrument) {
        Some((_low, _high, median)) => median * SPREAD_REJECT_MULTIPLE,
        None => SPREAD_BLACKOUT_ELEVATED_PIPS,
    }
}

/// The baked `(low, high, median)` pips for an instrument, or `None` when
/// it isn't in the baseline. Exposed so the reject path can name the
/// instrument's normal vs. current spread in the operator-facing message.
pub fn baked_baseline(instrument: &str) -> Option<(f64, f64, f64)> {
    baseline::SPREAD_BASELINE
        .binary_search_by(|(name, ..)| name.cmp(&instrument))
        .ok()
        .map(|i| {
            let (_, low, high, median, _n) = baseline::SPREAD_BASELINE[i];
            (low, high, median)
        })
}

/// Placeholder cutoff. A thin FX cross normally spreads ~2p and blows to
/// ~20p+ in the trough; 8p sits clearly above normal and below the
/// blowout. Majors (EUR/USD ~1p) never trip it, so the window is
/// self-scoping. Calibrate on demo before relying on it.
///
/// Provisional — see [`elevated_threshold_pips`] for the open question and
/// the hysteresis relationship to [`SPREAD_BLACKOUT_RECOVERED_PIPS`].
pub const SPREAD_BLACKOUT_ELEVATED_PIPS: f64 = 8.0;

/// "Recovered" spread cutoff in pips for the Sub-plan-2 recovery watcher
/// (`src/cron/blackout_watch.rs`). The spread is considered back to normal
/// once the sampled `ask − bid` (in pips) drops to/under this.
///
/// **Hysteresis (single tuning point):** lives here, beside the *elevated*
/// cutoff, so the two are tuned together and the invariant
/// `RECOVERED < ELEVATED` is visible in one file. Recovered sits **below**
/// elevated so the window doesn't flap right at the boundary: an entry is
/// blacked out above 8p, and the watcher only declares recovery once the
/// spread has fallen all the way back to ≤4p. Both are provisional and
/// MUST be calibrated together on demo — see [`elevated_threshold_pips`].
pub const SPREAD_BLACKOUT_RECOVERED_PIPS: f64 = 4.0;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn window_closed_never_rejects() {
        // Window closed ⇒ pass even with an absurdly wide spread, and the
        // wrapper never calls `get_quote` on this branch.
        assert!(!spread_blackout_decision(false, 50.0, 8.0));
    }

    #[test]
    fn window_open_wide_spread_rejects() {
        assert!(spread_blackout_decision(true, 20.0, 8.0));
    }

    #[test]
    fn window_open_tight_spread_passes() {
        assert!(!spread_blackout_decision(true, 2.0, 8.0));
    }

    #[test]
    fn boundary_exactly_at_threshold_passes() {
        // Strictly `>`, so exactly-at-threshold falls through (allowed).
        assert!(!spread_blackout_decision(true, 8.0, 8.0));
    }

    #[test]
    #[allow(clippy::assertions_on_constants)]
    fn recovered_cutoff_sits_below_elevated_for_hysteresis() {
        // The window must not flap at the boundary: recovery is only
        // declared once the spread has fallen below the (lower) recovered
        // cutoff, not the moment it dips under the elevated one. Constant
        // assertion on purpose — it guards the tuning invariant if a future
        // edit to either const inverts the pair.
        assert!(SPREAD_BLACKOUT_RECOVERED_PIPS < SPREAD_BLACKOUT_ELEVATED_PIPS);
    }

    #[test]
    fn unknown_instrument_falls_back_to_flat_constant() {
        // A made-up name can't be in the baked baseline → flat fallback.
        assert_eq!(
            elevated_threshold_pips("DEFINITELY NOT A REAL MARKET ZZZ"),
            SPREAD_BLACKOUT_ELEVATED_PIPS
        );
        assert_eq!(elevated_threshold_pips(""), SPREAD_BLACKOUT_ELEVATED_PIPS);
    }

    #[test]
    fn baked_baseline_is_sorted_and_self_consistent() {
        // The generated table must be sorted by name (binary_search relies
        // on it) and every row must satisfy low <= median <= high.
        let mut prev: Option<&str> = None;
        for (name, low, high, median, n) in baseline::SPREAD_BASELINE {
            if let Some(p) = prev {
                assert!(p < *name, "baseline not sorted: {p:?} !< {name:?}");
            }
            prev = Some(name);
            assert!(*n > 0, "{name}: zero samples");
            assert!(
                *low <= *median && *median <= *high,
                "{name}: low {low} median {median} high {high} not ordered",
            );
        }
    }

    #[test]
    fn baked_threshold_is_five_times_normal() {
        // For every baked instrument the threshold is exactly 5x its
        // median normal spread — high enough to pass resting/busy-news
        // widening, low enough to reject a ≥10x spread-hour blowout.
        for (name, _low, _high, median, _n) in baseline::SPREAD_BASELINE {
            let t = elevated_threshold_pips(name);
            assert!(
                (t - median * SPREAD_REJECT_MULTIPLE).abs() < 1e-9,
                "{name}: threshold {t} != 5x median {median}",
            );
        }
    }
}
