// @generated by bake-mt5. Account-scoped MT5 profiles; empty until calibration passes.
#[allow(clippy::type_complexity)]
pub static SPREAD_BASELINE_MT5: &[(&str, &str, &str, bool, u32, [f64; 24], f64, f64, f64, [f64; 24])] = &[];
