//! System 1 of the DST-aware spread blackout: reject a brand-new entry
//! that fires during the post-NY-close liquidity trough when the live
//! spread on the incoming instrument is elevated. Reject, not delay — the
//! next signal bar refires and re-checks (by then the spread may have
//! recovered).
//!
//! This is the **pure decision** (KV-free, broker-free, wasm-safe), so it
//! lives in `core` and is shared by BOTH consumers
//! (`[[strategy_changes_in_both_replayer_and_worker]]`):
//!
//! - the **live worker** wraps it with a KV window read + a live broker
//!   quote sample (`run_enter`, `src/lib.rs`);
//! - the **offline replay** wraps it with the fire-bar `ask_c − bid_c`
//!   spread from the recorded candle and an `is_ny_close_edge` stand-in for
//!   the window marker (`engine::simulate_fill`).
//!
//! Keeping the decision + the baked per-instrument baseline here is what
//! lets a replay 422 exactly the entries the live worker would 423.

/// Decide whether to reject an entry on spread-blackout grounds.
///
/// `window_open`  — the global `spread-blackout:window` marker is present
///                  (Sub-plan 2). When `false` we never sample the spread.
/// `spread_pips`  — live `ask − bid` for the incoming instrument, in pips.
/// `threshold_pips` — the "elevated" cutoff (see OPEN QUESTION on
///                  [`elevated_threshold_pips`]).
///
/// Returns `true` ⇒ REJECT (`rejected: spread-blackout`).
/// `false` ⇒ fall through to the normal entry (window closed, OR window
/// open but the spread is fine — that instrument/day is not blacked out).
///
/// Strictly `>`: a spread exactly at the threshold is allowed (the
/// boundary is deliberately permissive — see the boundary unit test).
pub fn spread_blackout_decision(window_open: bool, spread_pips: f64, threshold_pips: f64) -> bool {
    window_open && spread_pips > threshold_pips
}

/// The compile-time per-instrument spread baseline, generated by
/// `core/build.rs` from the `spread-sampler-cron` YAML samples. Each row is
/// `(tradenation_market_name, low_pips, high_pips, median_pips, n)`,
/// sorted by name. Empty when no samples are checked out (→ flat fallback).
mod baseline {
    include!(concat!(env!("OUT_DIR"), "/spread_baseline.rs"));
}

/// The reject line, as a multiple of an instrument's *normal* (median)
/// spread. The 2026-06-23 spread-hour data showed the post-NY-close
/// blowout is an **FX** phenomenon — FX crosses spike 10–20× their normal
/// (AUD/USD 0.4p → 6p, EUR/GBP 0.5p → 10p), while commodities/indices
/// (Copper, Gold) stay flat. So a per-instrument multiple of normal is the
/// right shape: 5× sits clearly above resting jitter and busy-news
/// widening, yet well below a real spread-hour spike (which is ≥10×), so it
/// catches the blowout. For a flat-spread instrument like Copper (normal
/// ~150p) the line is ~750p — never a false block.
///
/// Chosen over "observed max" because with a short sample window a quiet
/// instrument's max can equal its normal, which would re-introduce the
/// over-blocking this whole change fixed.
pub const SPREAD_REJECT_MULTIPLE: f64 = 5.0;

/// "Elevated" spread cutoff in pips for System 1's reject, per instrument.
///
/// Looks the instrument up in the baked baseline (keyed by the
/// broker-canonical TradeNation name — the same `resolved.instrument` the
/// gate passes). When found, the threshold is
/// `median × SPREAD_REJECT_MULTIPLE` (5× the instrument's own normal
/// spread) — see [`SPREAD_REJECT_MULTIPLE`].
///
/// Falls back to the flat [`SPREAD_BLACKOUT_ELEVATED_PIPS`] for any
/// instrument not in the baseline (a fresh asset, or one whose samples
/// lacked a pip size). Re-baked whenever the committed samples grow.
pub fn elevated_threshold_pips(instrument: &str) -> f64 {
    match baked_baseline(instrument) {
        Some((_low, _high, median)) => median * SPREAD_REJECT_MULTIPLE,
        None => SPREAD_BLACKOUT_ELEVATED_PIPS,
    }
}

/// The baked `(low, high, median)` pips for an instrument, or `None` when
/// it isn't in the baseline. Exposed so the reject path can name the
/// instrument's normal vs. current spread in the operator-facing message.
pub fn baked_baseline(instrument: &str) -> Option<(f64, f64, f64)> {
    baseline::SPREAD_BASELINE
        .binary_search_by(|(name, ..)| name.cmp(&instrument))
        .ok()
        .map(|i| {
            let (_, low, high, median, ..) = baseline::SPREAD_BASELINE[i];
            (low, high, median)
        })
}

/// The baked `(elevated_hours_mask, hour_widen_pips)` for an instrument, or
/// `None` when it isn't in the baseline. The mask's bit `h` = UTC hour `h`
/// is a learned spread hour; `hour_widen_pips[h]` is that hour's p90 widen
/// size (0.0 when not elevated). See `core/build.rs::spread_hours`.
fn baked_spread_hours(instrument: &str) -> Option<(u32, [f64; 24])> {
    baseline::SPREAD_BASELINE
        .binary_search_by(|(name, ..)| name.cmp(&instrument))
        .ok()
        .map(|i| {
            let (.., mask, widen) = baseline::SPREAD_BASELINE[i];
            (mask, widen)
        })
}

/// How many minutes ahead of an elevated hour's start we pre-emptively
/// widen an open stop. The spread spike is at the top of the hour; widening
/// ~30 min early means the stop is already out of the way before the spike
/// lands, rather than racing it. Shared constant so the worker cron and the
/// offline replay lead by the same amount.
pub const SPREAD_HOUR_LEAD_MINUTES: i64 = 30;

/// The pre-emptive widen size (in pips) for `instrument` at `now`, or `None`
/// when `now` is **not** in (or within [`SPREAD_HOUR_LEAD_MINUTES`] of the
/// start of) one of this instrument's learned spread hours.
///
/// Timing is entirely from baked history — no live spread read is needed to
/// decide *when* or *how much* to widen (the caller may still floor the
/// result by the live spread; see the System-2 consumer). The returned pips
/// is the elevated hour's baked p90.
///
/// Lead handling: if `now` is within the lead window of the *next* UTC hour
/// and that next hour is elevated, we return the next hour's widen (so the
/// stop is out of the way before the spike). Otherwise we return the current
/// hour's widen iff the current hour is elevated.
///
/// `None` for an instrument absent from the baseline, or one whose samples
/// yielded no learnable spread hours (mask 0) — the caller falls back to the
/// legacy [`is_ny_close_edge`](crate::ny_clock::is_ny_close_edge) gate for
/// those, so nothing regresses for un-sampled assets.
pub fn spread_hour_widen_pips(instrument: &str, now: chrono::DateTime<chrono::Utc>) -> Option<f64> {
    let (mask, widen) = baked_spread_hours(instrument)?;
    spread_hour_widen_for(mask, &widen, now)
}

/// Pure spread-hour-widen decision over an explicit `(mask, widen)` — the
/// unit-testable seam behind [`spread_hour_widen_pips`], free of the baked
/// table so tests can drive it with synthetic instrument shapes.
///
/// Returns the widen pips iff `now`'s hour is elevated, or `now` is within
/// [`SPREAD_HOUR_LEAD_MINUTES`] of the top of a next hour that is elevated
/// (look-ahead, so the stop is out of the way before the spike). `None`
/// otherwise (including a mask of 0).
fn spread_hour_widen_for(
    mask: u32,
    widen: &[f64; 24],
    now: chrono::DateTime<chrono::Utc>,
) -> Option<f64> {
    use chrono::Timelike;
    if mask == 0 {
        return None;
    }
    let hour = now.hour() as usize;
    // Within the lead window of the next hour's top? Then look ahead.
    let minutes_into_hour = now.minute() as i64;
    let lead_reaches_next = 60 - minutes_into_hour <= SPREAD_HOUR_LEAD_MINUTES;
    if lead_reaches_next {
        let next = (hour + 1) % 24;
        if mask & (1 << next) != 0 {
            return Some(widen[next]);
        }
    }
    if mask & (1 << hour) != 0 {
        return Some(widen[hour]);
    }
    None
}

/// Is `now` a spread hour for `instrument` (per-instrument, learned)? A thin
/// bool wrapper over [`spread_hour_widen_pips`]. Unknown instrument / no
/// learned hours ⇒ fall back to the legacy NY-close-edge gate so un-sampled
/// assets keep their prior behaviour.
pub fn is_spread_hour(instrument: &str, now: chrono::DateTime<chrono::Utc>) -> bool {
    match baked_spread_hours(instrument) {
        Some((mask, _)) if mask != 0 => spread_hour_widen_pips(instrument, now).is_some(),
        // No learned hours for this instrument → legacy fallback.
        _ => crate::ny_clock::is_ny_close_edge(now),
    }
}

/// Placeholder cutoff. A thin FX cross normally spreads ~2p and blows to
/// ~20p+ in the trough; 8p sits clearly above normal and below the
/// blowout. Majors (EUR/USD ~1p) never trip it, so the window is
/// self-scoping. Calibrate on demo before relying on it.
///
/// Provisional — see [`elevated_threshold_pips`] for the open question and
/// the hysteresis relationship to [`SPREAD_BLACKOUT_RECOVERED_PIPS`].
pub const SPREAD_BLACKOUT_ELEVATED_PIPS: f64 = 8.0;

/// "Recovered" spread cutoff in pips for the Sub-plan-2 recovery watcher
/// (`src/cron/blackout_watch.rs`). The spread is considered back to normal
/// once the sampled `ask − bid` (in pips) drops to/under this.
///
/// **Hysteresis (single tuning point):** lives here, beside the *elevated*
/// cutoff, so the two are tuned together and the invariant
/// `RECOVERED < ELEVATED` is visible in one file. Recovered sits **below**
/// elevated so the window doesn't flap right at the boundary: an entry is
/// blacked out above 8p, and the watcher only declares recovery once the
/// spread has fallen all the way back to ≤4p. Both are provisional and
/// MUST be calibrated together on demo — see [`elevated_threshold_pips`].
pub const SPREAD_BLACKOUT_RECOVERED_PIPS: f64 = 4.0;

/// Spread-blackout backstop, in seconds (~3h). Single source of truth: the
/// global window-marker TTL (apply), each per-trade record's TTL, and the
/// recovery watcher's "clear regardless of spread" backstop (watch) all derive
/// from this one constant so they can never drift apart. The post-NY-close
/// liquidity trough is ~1h; 3h is a generous safety ceiling after which a
/// still-`applied` record is force-cleared.
///
/// Lives in `core` (not the cron crate) so the offline replay's transient-widen
/// reconstruction (`engine::simulator::restore_bar`) computes the same backstop
/// as the live recovery watcher without depending on `trade-control-cron`. The
/// cron crate re-exports this as `constants::BLACKOUT_BACKSTOP_SECONDS`.
pub const BLACKOUT_BACKSTOP_SECONDS: u64 = 3 * 60 * 60;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn window_closed_never_rejects() {
        // Window closed ⇒ pass even with an absurdly wide spread, and the
        // wrapper never calls `get_quote` on this branch.
        assert!(!spread_blackout_decision(false, 50.0, 8.0));
    }

    #[test]
    fn window_open_wide_spread_rejects() {
        assert!(spread_blackout_decision(true, 20.0, 8.0));
    }

    #[test]
    fn window_open_tight_spread_passes() {
        assert!(!spread_blackout_decision(true, 2.0, 8.0));
    }

    #[test]
    fn boundary_exactly_at_threshold_passes() {
        // Strictly `>`, so exactly-at-threshold falls through (allowed).
        assert!(!spread_blackout_decision(true, 8.0, 8.0));
    }

    #[test]
    #[allow(clippy::assertions_on_constants)]
    fn recovered_cutoff_sits_below_elevated_for_hysteresis() {
        // The window must not flap at the boundary: recovery is only
        // declared once the spread has fallen below the (lower) recovered
        // cutoff, not the moment it dips under the elevated one. Constant
        // assertion on purpose — it guards the tuning invariant if a future
        // edit to either const inverts the pair.
        assert!(SPREAD_BLACKOUT_RECOVERED_PIPS < SPREAD_BLACKOUT_ELEVATED_PIPS);
    }

    #[test]
    fn unknown_instrument_falls_back_to_flat_constant() {
        // A made-up name can't be in the baked baseline → flat fallback.
        assert_eq!(
            elevated_threshold_pips("DEFINITELY NOT A REAL MARKET ZZZ"),
            SPREAD_BLACKOUT_ELEVATED_PIPS
        );
        assert_eq!(elevated_threshold_pips(""), SPREAD_BLACKOUT_ELEVATED_PIPS);
    }

    #[test]
    fn baked_baseline_is_sorted_and_self_consistent() {
        // The generated table must be sorted by name (binary_search relies
        // on it) and every row must satisfy low <= median <= high.
        let mut prev: Option<&str> = None;
        for (name, low, high, median, n, mask, widen) in baseline::SPREAD_BASELINE {
            if let Some(p) = prev {
                assert!(p < *name, "baseline not sorted: {p:?} !< {name:?}");
            }
            prev = Some(name);
            assert!(*n > 0, "{name}: zero samples");
            assert!(
                *low <= *median && *median <= *high,
                "{name}: low {low} median {median} high {high} not ordered",
            );
            // Mask/widen coherence: an elevated hour must carry a positive
            // widen, and a non-elevated hour must bake 0.0 (nothing to widen
            // by). This guards the build.rs render against drift.
            for h in 0..24 {
                let elevated = mask & (1 << h) != 0;
                let w = widen[h];
                if elevated {
                    assert!(w > 0.0, "{name}: hour {h} elevated but widen {w} <= 0");
                } else {
                    assert!(w == 0.0, "{name}: hour {h} not elevated but widen {w} != 0");
                }
            }
        }
    }

    #[test]
    fn baked_threshold_is_five_times_normal() {
        // For every baked instrument the threshold is exactly 5x its
        // median normal spread — high enough to pass resting/busy-news
        // widening, low enough to reject a ≥10x spread-hour blowout.
        for (name, _low, _high, median, ..) in baseline::SPREAD_BASELINE {
            let t = elevated_threshold_pips(name);
            assert!(
                (t - median * SPREAD_REJECT_MULTIPLE).abs() < 1e-9,
                "{name}: threshold {t} != 5x median {median}",
            );
        }
    }

    // --- spread-hour widen lookup (pure seam, synthetic tables) ---

    use chrono::{DateTime, Utc};

    fn ts(s: &str) -> DateTime<Utc> {
        s.parse().expect("valid rfc3339 fixture")
    }

    /// A EUR/USD-shaped mask: a single spike hour (21:00 UTC), widen 5p.
    fn eurusd_shape() -> (u32, [f64; 24]) {
        let mut w = [0.0; 24];
        w[21] = 5.0;
        (1 << 21, w)
    }

    /// A Gold-shaped mask: a structural overnight block (18:00–06:00 UTC),
    /// widen 75p across the block.
    fn gold_shape() -> (u32, [f64; 24]) {
        let mut mask = 0u32;
        let mut w = [0.0; 24];
        for h in (18..24).chain(0..7) {
            mask |= 1 << h;
            w[h] = 75.0;
        }
        (mask, w)
    }

    #[test]
    fn widen_fires_inside_the_elevated_hour() {
        let (m, w) = eurusd_shape();
        // 21:15 UTC — squarely inside the elevated hour.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T21:15:00Z")),
            Some(5.0),
        );
    }

    #[test]
    fn widen_none_outside_any_elevated_hour() {
        let (m, w) = eurusd_shape();
        // Midday, nowhere near 21:00.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T12:00:00Z")),
            None
        );
    }

    #[test]
    fn widen_leads_into_the_next_elevated_hour() {
        let (m, w) = eurusd_shape();
        // 20:35 UTC — 25 min before 21:00, inside the 30-min lead → widen now.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T20:35:00Z")),
            Some(5.0),
        );
        // 20:29 UTC — 31 min before, just outside the lead → not yet.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T20:29:00Z")),
            None
        );
    }

    #[test]
    fn widen_lead_wraps_across_midnight() {
        // Gold's block includes hour 0. At 23:40 UTC the next hour (0) is
        // elevated and within the lead → widen, exercising the (h+1)%24 wrap.
        let (m, w) = gold_shape();
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T23:40:00Z")),
            Some(75.0),
        );
    }

    #[test]
    fn widen_covers_a_structural_overnight_block() {
        let (m, w) = gold_shape();
        // Deep in the overnight block.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T02:00:00Z")),
            Some(75.0),
        );
        // Daytime, block is closed.
        assert_eq!(
            spread_hour_widen_for(m, &w, ts("2026-07-01T12:00:00Z")),
            None
        );
    }

    #[test]
    fn widen_empty_mask_never_fires() {
        // A flat-fat-tail instrument bakes mask 0 → never a spread hour.
        assert_eq!(
            spread_hour_widen_for(0, &[0.0; 24], ts("2026-07-01T21:15:00Z")),
            None
        );
    }

    #[test]
    fn is_spread_hour_unknown_instrument_falls_back_to_ny_close() {
        // No baseline row → fall back to the legacy NY-close-edge gate.
        // 12-Mar-2026 is EDT, close edge 21:00 UTC.
        assert!(is_spread_hour(
            "DEFINITELY NOT A REAL MARKET ZZZ",
            ts("2026-03-12T21:00:00Z")
        ));
        // A non-edge hour on the same (unknown) instrument → false.
        assert!(!is_spread_hour(
            "DEFINITELY NOT A REAL MARKET ZZZ",
            ts("2026-03-12T10:00:00Z")
        ));
    }
}
