// @generated by spread-baseline-gen. Do not edit.
// Candle-derived, per-broker spread-hour masks (med3 + peak-frac).
// (broker, symbol, schedule, reviewed, elevated_hours_mask, hour_widen_frac[24]), sorted by (broker, symbol).
// `schedule` is the spread-schedule FK name whose LOCAL wall-clock hour the
// mask is bucketed in — the gate DST-shifts the mask to UTC at read time.
// `reviewed = true` ⇒ analysed with enough data; an empty mask then means
// GENUINELY no spread hour. `reviewed = false` ⇒ insufficient data, mask is 0,
// gate should fall back to its NY-close-edge default.
//
// NOTE (Stage 3): this committed table is a small hand-authored PLACEHOLDER so
// `core` compiles + its tests run against a known shape. The orchestrator
// overwrites the whole file with the real `spread-baseline-gen` regen after the
// DST-aware read path lands. Rows here exist only to be internally consistent
// with the schedule-local mask semantics (mask bit = LOCAL hour of the row's
// `schedule` tz), NOT to reflect live data.
#[allow(clippy::type_complexity)]
pub static SPREAD_BASELINE_CANDLE: &[(&str, &str, &str, bool, u32, [f64; 24])] = &[
    // ny FX cross, single 17:00-LOCAL spike (NY close). Mask bit 17 = 5pm New York.
    // Under EDT that is 21:00 UTC, under EST 22:00 UTC — same local bit, DST-shifted.
    (
        "oanda",
        "AUD_CHF",
        "ny",
        true,
        1 << 17,
        widen_at(17, 0.0027),
    ),
    // A ny FX cross with a two-hour local block (17:00 + 18:00 local).
    (
        "oanda",
        "GBP_AUD",
        "ny",
        true,
        (1 << 17) | (1 << 18),
        widen_two(17, 0.0019, 18, 0.0016),
    ),
    // A ny-scheduled index (US 500-shaped): 16:00 local cash-close spike.
    ("oanda", "SPX500_USD", "ny", true, 1 << 16, widen_at(16, 3.5)),
    // A tokyo-scheduled Asian index (Nikkei-shaped): fixed-UTC-ish tz with no
    // US-style DST, spike at 15:00 Tokyo (JST is UTC+9 year-round → 06:00 UTC).
    ("oanda", "JP225_USD", "tokyo", true, 1 << 15, widen_at(15, 8.0)),
    // A reviewed-but-genuinely-flat instrument (mask 0 → NY-close-edge fallback).
    (
        "oanda",
        "BTC_USD",
        "none",
        true,
        0,
        [0.0; 24],
    ),
    // Insufficient data: reviewed=false, mask 0 → NY-close-edge fallback.
    (
        "oanda",
        "EUR_TRY",
        "ny",
        false,
        0,
        [0.0; 24],
    ),
    // TradeNation-named ny FX cross, 17:00-local spike (mirrors AUD/CHF).
    (
        "tradenation",
        "AUD/CHF",
        "ny",
        true,
        1 << 17,
        widen_at(17, 0.0027),
    ),
    // TradeNation EUR/USD, single 17:00-local NY-close spike.
    (
        "tradenation",
        "EUR/USD",
        "ny",
        true,
        1 << 17,
        widen_at(17, 0.0006),
    ),
    // TradeNation GBP/AUD, single 17:00-local NY-close spike.
    (
        "tradenation",
        "GBP/AUD",
        "ny",
        true,
        1 << 17,
        widen_at(17, 0.0019),
    ),
];

/// Build a widen-frac array with a single non-zero hour (placeholder helper —
/// keeps the fixture rows readable; the real regen inlines full 24-slot arrays).
const fn widen_at(hour: usize, frac: f64) -> [f64; 24] {
    let mut w = [0.0; 24];
    w[hour] = frac;
    w
}

/// Build a widen-frac array with two non-zero hours (placeholder helper).
const fn widen_two(h1: usize, f1: f64, h2: usize, f2: f64) -> [f64; 24] {
    let mut w = [0.0; 24];
    w[h1] = f1;
    w[h2] = f2;
    w
}
