//! Render the computed per-broker rows into a committed `spread_baseline.rs`
//! table.
//!
//! The generated table mirrors the shape `core/build.rs` produces today so the
//! eventual gate-swap (a later stage) is a data-source change, not a schema
//! change. Row tuple:
//!
//! `(broker, symbol, elevated_hours_mask, hour_widen_frac[24])`
//!
//! sorted by `(broker, symbol)` so the gate can binary-search. The widen is a
//! **spread fraction** (`spread/mid`), not pips — a scale-free unit that works
//! for FX, metals, and indices alike. (The current sampler table bakes pips;
//! the gate-swap stage translates the System-2 widen consumer to fractions.)

use crate::BaselineRow;

/// Render the sorted rows into a Rust source file.
///
/// Rows are sorted by `(broker, symbol)` and **deduplicated on that key** — the
/// gate binary-searches the table, so a duplicate key would make lookups
/// non-deterministic. Duplicates arise legitimately: two catalog assets can
/// share one broker MarketName (e.g. two `Spot Gold` ids). We keep the first
/// occurrence (identical instrument ⇒ identical profile) and warn on any that
/// disagree, so a real conflict surfaces rather than being silently dropped.
pub fn render_table(rows: &[BaselineRow]) -> String {
    let mut sorted: Vec<&BaselineRow> = rows.iter().collect();
    sorted.sort_by(|a, b| {
        (a.broker.as_str(), a.symbol.as_str()).cmp(&(b.broker.as_str(), b.symbol.as_str()))
    });
    sorted.dedup_by(|b, a| {
        // `dedup_by` keeps `a` (the earlier element) and drops `b` when they
        // match. Compare on the (broker, symbol) key.
        let same_key = a.broker == b.broker && a.symbol == b.symbol;
        if same_key && a.profile.elevated_hours != b.profile.elevated_hours {
            tracing::warn!(
                "duplicate key {} {} with DIFFERENT masks ({} vs {}) — keeping first",
                a.broker.as_str(),
                a.symbol,
                a.profile.elevated_hours,
                b.profile.elevated_hours,
            );
        }
        same_key
    });

    let mut s = String::new();
    s.push_str("// @generated by spread-baseline-gen. Do not edit.\n");
    s.push_str("// Candle-derived, per-broker spread-hour masks (med3 + peak-frac).\n");
    s.push_str(
        "// (broker, symbol, reviewed, elevated_hours_mask, hour_widen_frac[24]), \
         sorted by (broker, symbol).\n",
    );
    s.push_str(
        "// `reviewed = true` ⇒ analysed with enough data; an empty mask then \
         means\n// GENUINELY no spread hour. `reviewed = false` ⇒ insufficient \
         data, mask is 0,\n// gate should fall back to its NY-close-edge \
         default.\n",
    );
    s.push_str("#[allow(clippy::type_complexity)]\n");
    s.push_str("pub static SPREAD_BASELINE_CANDLE: &[(&str, &str, bool, u32, [f64; 24])] = &[\n");
    for r in &sorted {
        let sym = escape(&r.symbol);
        let reviewed = matches!(r.profile.review, crate::compute::ReviewStatus::Reviewed);
        let widen = r
            .profile
            .hour_widen_frac
            .iter()
            .map(|f| format!("{f:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        s.push_str(&format!(
            "    (\"{}\", \"{sym}\", {reviewed}, {}, [{widen}]),\n",
            r.broker.as_str(),
            r.profile.elevated_hours,
        ));
    }
    s.push_str("];\n");
    s
}

/// Escape a symbol for a Rust string literal. Broker symbols contain spaces,
/// slashes, parens — none need escaping except a backslash or quote, which
/// broker symbols don't contain, but be safe.
fn escape(name: &str) -> String {
    name.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compute::ReviewStatus;
    use crate::{Broker, SpreadProfile};

    fn row(broker: Broker, symbol: &str, mask: u32) -> BaselineRow {
        let mut profile = SpreadProfile::empty(1000);
        profile.elevated_hours = mask;
        // A row carrying a computed mask is a Reviewed verdict.
        profile.review = ReviewStatus::Reviewed;
        BaselineRow {
            broker,
            symbol: symbol.to_string(),
            display_name: symbol.to_string(),
            profile,
        }
    }

    #[test]
    fn renders_sorted_per_broker_rows() {
        let rows = vec![
            row(Broker::TradeNation, "EUR/USD", 1 << 21),
            row(Broker::Oanda, "EUR_USD", 1 << 21),
        ];
        let out = render_table(&rows);
        // OANDA sorts before TradeNation; both symbols present as distinct keys.
        let oanda_at = out.find("\"oanda\", \"EUR_USD\"").expect("oanda row");
        let tn_at = out.find("\"tradenation\", \"EUR/USD\"").expect("tn row");
        assert!(oanda_at < tn_at, "oanda row must sort before tradenation");
        assert!(out.contains("2097152")); // 1 << 21
        assert!(
            out.contains("\"EUR_USD\", true,"),
            "reviewed column renders"
        );
    }

    #[test]
    fn insufficient_data_renders_reviewed_false() {
        // A raw empty() profile (thin data) must render `reviewed = false` so a
        // consumer can distinguish it from a reviewed-but-flat instrument.
        let rows = vec![BaselineRow {
            broker: Broker::Oanda,
            symbol: "THIN".to_string(),
            display_name: "THIN".to_string(),
            profile: SpreadProfile::empty(10),
        }];
        let out = render_table(&rows);
        assert!(
            out.contains("\"THIN\", false, 0,"),
            "thin data → reviewed=false"
        );
    }

    #[test]
    fn renders_empty_table() {
        let out = render_table(&[]);
        assert!(out.contains("SPREAD_BASELINE_CANDLE"));
        assert!(out.contains("&[\n];\n"));
    }

    #[test]
    fn dedups_same_broker_symbol_key() {
        // Two catalog assets sharing one broker MarketName (e.g. two Spot Gold
        // ids) must produce ONE table row — the gate binary-searches the key.
        let rows = vec![
            row(Broker::TradeNation, "Spot Gold", 0),
            row(Broker::TradeNation, "Spot Gold", 0),
        ];
        let out = render_table(&rows);
        assert_eq!(
            out.matches("\"tradenation\", \"Spot Gold\"").count(),
            1,
            "duplicate (broker, symbol) key must collapse to one row"
        );
    }
}
