//! Render the computed per-broker rows into a committed `spread_baseline.rs`
//! table.
//!
//! The generated table mirrors the shape `core/build.rs` produces today so the
//! eventual gate-swap (a later stage) is a data-source change, not a schema
//! change. Row tuple:
//!
//! `(broker, symbol, schedule, reviewed, elevated_hours_mask, hour_widen_frac[24],
//!   baseline_median_pips, baseline_low_pips, baseline_high_pips,
//!   hour_p90_frac[24])`
//!
//! sorted by `(broker, symbol)` so the gate can binary-search. The widen is a
//! **spread fraction** (`spread/mid`), not pips — a scale-free unit that works
//! for FX, metals, and indices alike. The three trailing `*_pips` columns are
//! the whole-window spread MAGNITUDE baseline in pips (median/low/high), the
//! reject-threshold source the live gate reads (`median × SPREAD_REJECT_MULTIPLE`);
//! `median` is placed first as the primary field. They are appended at the END
//! so existing column positions stay stable.
//!
//! # `hour_widen_frac` vs `hour_p90_frac` — two different questions
//!
//! These look alike and are easy to confuse; keeping them apart is the point of
//! the second column.
//!
//! - **`hour_widen_frac[h]`** — GATED. Non-zero only for hours in
//!   `elevated_hours_mask`; zero at the other 23. It answers *"is this a flagged
//!   spread hour, and if so how far do we widen an open stop?"* The presence of a
//!   value **is** the gate.
//! - **`hour_p90_frac[h]`** — UNGATED. The p90 spread fraction for **every**
//!   hour that had enough samples, flagged or not. It answers *"what spread do I
//!   expect at hour h?"* — a forecast, with no notion of elevation.
//!
//! The forecast is what the forward-looking SL floor consumes
//! (`max(10×last_candle_spread, 10×expected_hour_spread, desired_sl)`), so a stop
//! is sized for the spread it will actually meet rather than for a clock proxy.
//! The generator has always computed p90 for all 24 hours; it was simply never
//! emitted, because `apply_gates` copies it into `hour_widen_frac` only inside
//! the flag branch. Nothing about flagging changes here: the flag statistic is
//! p75 (`FLAG_PERCENTILE`) and the widen is p90 (`WIDEN_PERCENTILE`), so emitting
//! the ungated p90 alongside leaves every existing consumer byte-identical.

use crate::BaselineRow;

/// Render the sorted rows into a Rust source file.
///
/// Rows are sorted by `(broker, symbol)` and **deduplicated on that key** — the
/// gate binary-searches the table, so a duplicate key would make lookups
/// non-deterministic. Duplicates arise legitimately: two catalog assets can
/// share one broker MarketName (e.g. two `Spot Gold` ids). We keep the first
/// occurrence (identical instrument ⇒ identical profile) and warn on any that
/// disagree, so a real conflict surfaces rather than being silently dropped.
pub fn render_table(rows: &[BaselineRow]) -> String {
    let mut sorted: Vec<&BaselineRow> = rows.iter().collect();
    sorted.sort_by(|a, b| {
        (a.broker.as_str(), a.symbol.as_str()).cmp(&(b.broker.as_str(), b.symbol.as_str()))
    });
    sorted.dedup_by(|b, a| {
        // `dedup_by` keeps `a` (the earlier element) and drops `b` when they
        // match. Compare on the (broker, symbol) key.
        let same_key = a.broker == b.broker && a.symbol == b.symbol;
        if same_key && a.profile.elevated_hours != b.profile.elevated_hours {
            tracing::warn!(
                "duplicate key {} {} with DIFFERENT masks ({} vs {}) — keeping first",
                a.broker.as_str(),
                a.symbol,
                a.profile.elevated_hours,
                b.profile.elevated_hours,
            );
        }
        same_key
    });

    let mut s = String::new();
    s.push_str("// @generated by spread-baseline-gen. Do not edit.\n");
    s.push_str("// Candle-derived, per-broker spread-hour masks (med3 + peak-frac).\n");
    s.push_str(
        "// (broker, symbol, schedule, reviewed, elevated_hours_mask, \
         hour_widen_frac[24],\n// baseline_median_pips, baseline_low_pips, \
         baseline_high_pips), sorted by (broker, symbol).\n",
    );
    s.push_str(
        "// `schedule` is the spread-schedule FK name whose LOCAL wall-clock \
         hour the\n// mask is bucketed in — the gate DST-shifts the mask to UTC \
         at read time.\n",
    );
    s.push_str(
        "// `reviewed = true` ⇒ analysed with enough data; an empty mask then \
         means\n// GENUINELY no spread hour. `reviewed = false` ⇒ insufficient \
         data, mask is 0,\n// gate should fall back to its NY-close-edge \
         default.\n",
    );
    s.push_str(
        "// `hour_widen_frac` is GATED (zero outside the mask — its presence IS the \
         gate);\n// `hour_p90_frac` is the UNGATED per-hour spread FORECAST for all 24 \
         hours.\n// Don't conflate them: one asks \"is this an elevated hour?\", the other \
         \"what\n// spread do I expect here?\". See the module docs.\n",
    );
    s.push_str("#[allow(clippy::type_complexity)]\n");
    s.push_str(
        "pub static SPREAD_BASELINE_CANDLE: &[(&str, &str, &str, bool, u32, [f64; 24], \
         f64, f64, f64, [f64; 24])] = &[\n",
    );
    for r in &sorted {
        let sym = escape(&r.symbol);
        let sched = escape(&r.spread_schedule);
        let reviewed = matches!(r.profile.review, crate::compute::ReviewStatus::Reviewed);
        let widen = render_hours(&r.profile.hour_widen_frac);
        let forecast = render_hours(&r.profile.hour_p90_frac);
        let median_pips = r.profile.baseline_median_pips;
        let low_pips = r.profile.baseline_low_pips;
        let high_pips = r.profile.baseline_high_pips;
        s.push_str(&format!(
            "    (\"{}\", \"{sym}\", \"{sched}\", {reviewed}, {}, [{widen}], \
             {median_pips:?}, {low_pips:?}, {high_pips:?}, [{forecast}]),\n",
            r.broker.as_str(),
            r.profile.elevated_hours,
        ));
    }
    s.push_str("];\n");
    s
}

/// Render a 24-hour fraction array as the body of a Rust array literal.
///
/// `{:?}` (not `{}`) so a float round-trips exactly — `1e-5` formats as `1e-5`
/// rather than `0.00001`, and the value parses back bit-identical.
fn render_hours(hours: &[f64; 24]) -> String {
    hours
        .iter()
        .map(|f| format!("{f:?}"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Escape a symbol for a Rust string literal. Broker symbols contain spaces,
/// slashes, parens — none need escaping except a backslash or quote, which
/// broker symbols don't contain, but be safe.
fn escape(name: &str) -> String {
    name.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compute::ReviewStatus;
    use crate::{Broker, SpreadProfile};

    fn row(broker: Broker, symbol: &str, mask: u32) -> BaselineRow {
        let mut profile = SpreadProfile::empty(1000);
        profile.elevated_hours = mask;
        // A row carrying a computed mask is a Reviewed verdict.
        profile.review = ReviewStatus::Reviewed;
        BaselineRow {
            broker,
            symbol: symbol.to_string(),
            display_name: symbol.to_string(),
            spread_schedule: "ny".to_string(),
            profile,
        }
    }

    #[test]
    fn renders_sorted_per_broker_rows() {
        let rows = vec![
            row(Broker::TradeNation, "EUR/USD", 1 << 21),
            row(Broker::Oanda, "EUR_USD", 1 << 21),
        ];
        let out = render_table(&rows);
        // OANDA sorts before TradeNation; both symbols present as distinct keys.
        let oanda_at = out.find("\"oanda\", \"EUR_USD\"").expect("oanda row");
        let tn_at = out.find("\"tradenation\", \"EUR/USD\"").expect("tn row");
        assert!(oanda_at < tn_at, "oanda row must sort before tradenation");
        assert!(out.contains("2097152")); // 1 << 21
        assert!(
            out.contains("\"EUR_USD\", \"ny\", true,"),
            "schedule + reviewed columns render"
        );
    }

    #[test]
    fn renders_baseline_pips_columns_at_the_end() {
        let mut profile = SpreadProfile::empty(1000);
        profile.review = ReviewStatus::Reviewed;
        profile.baseline_median_pips = 2.5;
        profile.baseline_low_pips = 1.0;
        profile.baseline_high_pips = 6.0;
        let rows = vec![BaselineRow {
            broker: Broker::Oanda,
            symbol: "EUR_USD".to_string(),
            display_name: "EUR_USD".to_string(),
            spread_schedule: "ny".to_string(),
            profile,
        }];
        let out = render_table(&rows);
        // The three pips columns render (median, low, high) between the widen
        // array and the trailing forecast array — column POSITION is the
        // contract, since consumers destructure the tuple positionally.
        assert!(
            out.contains("], 2.5, 1.0, 6.0, ["),
            "median/low/high pips must sit between the widen and forecast arrays, got:\n{out}"
        );
        // The type signature: three f64 columns, then the forecast array.
        assert!(out.contains("[f64; 24], f64, f64, f64, [f64; 24])"));
    }

    /// The forecast column must be **ungated**: populated for every hour that
    /// had samples, including hours absent from `elevated_hours`. This is the
    /// whole point of the second array — the gated `hour_widen_frac` is zero at
    /// those hours, so a forward-looking floor reading it would size every calm
    /// hour off 0.0 and silently degrade to today's reactive-only behaviour.
    #[test]
    fn forecast_column_is_ungated_where_widen_is_gated() {
        let mut profile = SpreadProfile::empty(1000);
        profile.review = ReviewStatus::Reviewed;
        // Hour 21 is flagged; hour 3 is a perfectly ordinary hour.
        profile.elevated_hours = 1 << 21;
        profile.hour_widen_frac[21] = 0.00042;
        // The forecast knows BOTH hours — that's the ungated data.
        profile.hour_p90_frac[21] = 0.00042;
        profile.hour_p90_frac[3] = 0.00007;
        let rows = vec![BaselineRow {
            broker: Broker::Oanda,
            symbol: "EUR_USD".to_string(),
            display_name: "EUR_USD".to_string(),
            spread_schedule: "ny".to_string(),
            profile,
        }];
        let out = render_table(&rows);

        // Parse the two arrays back out rather than substring-matching, so the
        // test proves the VALUES land in the right columns.
        let arrays: Vec<Vec<f64>> = out
            .lines()
            .find(|l| l.contains("\"EUR_USD\""))
            .map(|line| {
                line.match_indices('[')
                    .filter_map(|(i, _)| {
                        let rest = &line[i + 1..];
                        rest.find(']').map(|end| {
                            rest[..end]
                                .split(',')
                                .filter_map(|t| t.trim().parse::<f64>().ok())
                                .collect()
                        })
                    })
                    .collect()
            })
            .unwrap_or_default();
        assert_eq!(arrays.len(), 2, "expected widen + forecast arrays:\n{out}");
        let (widen, forecast) = (&arrays[0], &arrays[1]);

        // The GATED column: hour 3 is zeroed because it isn't flagged.
        assert_eq!(widen[3], 0.0, "widen must stay gated at an unflagged hour");
        assert_eq!(widen[21], 0.00042);
        // The UNGATED column: hour 3 carries its real forecast.
        assert_eq!(
            forecast[3], 0.00007,
            "forecast must be populated at an UNFLAGGED hour — that is the \
             entire reason this column exists"
        );
        assert_eq!(forecast[21], 0.00042);
    }

    #[test]
    fn insufficient_data_renders_reviewed_false() {
        // A raw empty() profile (thin data) must render `reviewed = false` so a
        // consumer can distinguish it from a reviewed-but-flat instrument.
        let rows = vec![BaselineRow {
            broker: Broker::Oanda,
            symbol: "THIN".to_string(),
            display_name: "THIN".to_string(),
            spread_schedule: "ny".to_string(),
            profile: SpreadProfile::empty(10),
        }];
        let out = render_table(&rows);
        assert!(
            out.contains("\"THIN\", \"ny\", false, 0,"),
            "thin data → reviewed=false"
        );
    }

    #[test]
    fn renders_empty_table() {
        let out = render_table(&[]);
        assert!(out.contains("SPREAD_BASELINE_CANDLE"));
        assert!(out.contains("&[\n];\n"));
    }

    #[test]
    fn dedups_same_broker_symbol_key() {
        // Two catalog assets sharing one broker MarketName (e.g. two Spot Gold
        // ids) must produce ONE table row — the gate binary-searches the key.
        let rows = vec![
            row(Broker::TradeNation, "Spot Gold", 0),
            row(Broker::TradeNation, "Spot Gold", 0),
        ];
        let out = render_table(&rows);
        assert_eq!(
            out.matches("\"tradenation\", \"Spot Gold\"").count(),
            1,
            "duplicate (broker, symbol) key must collapse to one row"
        );
    }
}
