//! Render the computed per-venue rows into a committed `market_hours_baked.rs`
//! table for `core` to `include!`.
//!
//! # Row shape
//!
//! `(venue, symbol, reviewed, daily_close_hours[6])`
//!
//! sorted by `(venue, symbol)` for a linear/binary scan. Fields:
//!
//! - `venue` — `"oanda"` | `"tradenation"`.
//! - `symbol` — the venue-native symbol string.
//! - `reviewed` — `true` when the instrument had enough gap events to trust the
//!   daily-close decision; `false` ⇒ too few samples / fetch error, treated as
//!   weekend-only.
//! - `daily_close_hours` — a fixed `[u32; 6]` of UTC hours to block daily, with
//!   the sentinel `NO_HOUR` (`u32::MAX`) padding unused slots. Empty (all
//!   sentinel) ⇒ weekend-only. Six slots is ample (observed clusters are 1–2
//!   adjacent hours; six leaves headroom).
//!
//! The **weekend block is NOT in the table** — it is universal (every
//! instrument halts Fri→Mon), so `core` applies it to every row unconditionally
//! and the table only carries the per-instrument daily-close overlay.

use std::collections::BTreeSet;

use crate::MarketHoursRow;

/// Number of daily-close-hour slots per row. Observed clusters are 1–2 adjacent
/// hours; six leaves comfortable headroom.
pub const HOUR_SLOTS: usize = 6;

/// Sentinel for an unused daily-close-hour slot.
pub const NO_HOUR: u32 = u32::MAX;

/// Render the sorted, de-duplicated rows into a Rust source file.
pub fn render_table(rows: &[MarketHoursRow]) -> String {
    let mut sorted: Vec<&MarketHoursRow> = rows.iter().collect();
    sorted.sort_by(|a, b| {
        (a.venue.as_str(), a.symbol.as_str()).cmp(&(b.venue.as_str(), b.symbol.as_str()))
    });
    // Dedup on (venue, symbol): the gate scans the table, a duplicate key would
    // make lookups ambiguous. Two catalog assets can share one venue symbol;
    // keep the first (identical instrument ⇒ identical profile).
    let mut seen: BTreeSet<(&str, &str)> = BTreeSet::new();
    sorted.retain(|r| seen.insert((r.venue.as_str(), r.symbol.as_str())));

    let mut s = String::new();
    s.push_str("// @generated by market-hours-gen. Do not edit.\n");
    s.push_str(
        "// Candle-derived, per-venue market-hours blackout overlay (ATR-gap \
         method).\n",
    );
    s.push_str(
        "// (venue, symbol, reviewed, daily_close_hours[6]), sorted by (venue, \
         symbol).\n",
    );
    s.push_str(
        "// The WEEKEND block (Fri-close -> Mon-open) is universal and applied \
         by `core`\n// to every instrument; this table carries only the \
         per-instrument DAILY-close\n// overlay. `daily_close_hours` are UTC \
         hours to block each day, padded with\n// u32::MAX. All-MAX ⇒ \
         weekend-only. `reviewed = false` ⇒ too few gap samples\n// (or fetch \
         error) to trust a daily-close decision — weekend-only, but flagged.\n",
    );
    s.push_str("#[allow(clippy::type_complexity)]\n");
    s.push_str("pub static MARKET_HOURS_BAKED: &[(&str, &str, bool, [u32; 6])] = &[\n");

    for r in &sorted {
        let reviewed = r.error.is_none() && r.profile.total_gaps >= crate::compute::MIN_SAMPLES;
        let hours = padded_hours(&r.profile.daily_close_hours);
        let hours_lit = hours
            .iter()
            .map(|h| {
                if *h == NO_HOUR {
                    "u32::MAX".to_string()
                } else {
                    h.to_string()
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        s.push_str(&format!(
            "    ({:?}, {:?}, {}, [{}]),\n",
            r.venue.as_str(),
            r.symbol,
            reviewed,
            hours_lit,
        ));
    }
    s.push_str("];\n");
    s
}

/// Pad (or truncate) the daily-close hours into a fixed `[u32; HOUR_SLOTS]`
/// with `NO_HOUR` sentinels. Truncation only bites if an instrument somehow had
/// more than six dominant close hours, which the `dominant_hours` cutoff makes
/// impossible in practice; we log-truncate rather than panic.
fn padded_hours(hours: &[u32]) -> [u32; HOUR_SLOTS] {
    let mut out = [NO_HOUR; HOUR_SLOTS];
    for (slot, &h) in out.iter_mut().zip(hours.iter()) {
        *slot = h;
    }
    if hours.len() > HOUR_SLOTS {
        tracing::warn!(
            "daily_close_hours {:?} exceeds {HOUR_SLOTS} slots — truncated",
            hours
        );
    }
    out
}

/// Render the measured session spans into `core/src/session_hours_baked.rs`.
/// Only instruments WITH a span get a row; everything else (24h markets, split
/// sessions, thin history, fetch errors) is absent, and absent means "never
/// closed" to the gate — it fails open.
pub fn render_session_table(rows: &[MarketHoursRow]) -> String {
    let mut spans: Vec<(&str, &str, &crate::session::SessionSpan)> = rows
        .iter()
        .filter_map(|r| {
            Some((
                r.venue.as_str(),
                r.symbol.as_str(),
                r.session.as_ref().ok()?,
            ))
        })
        .collect();
    spans.sort_by(|a, b| (a.0, a.1).cmp(&(b.0, b.1)));
    spans.dedup_by(|b, a| (a.0, a.1) == (b.0, b.1));

    let mut s = String::new();
    s.push_str("// @generated by market-hours-gen. Do not edit.\n");
    s.push_str("// Candle-derived trading SESSION of each session-bound instrument, per venue.\n");
    s.push_str("// (venue, symbol, timezone, start_hour, hours): the market trades\n");
    s.push_str("// [start_hour, start_hour + hours) on the LOCAL wall clock of `timezone`,\n");
    s.push_str("// Mon-Fri. An instrument with no row is never treated as closed (24h market,\n");
    s.push_str("// split session, or too little history to trust).\n");
    s.push_str("pub static SESSION_HOURS_BAKED: &[(&str, &str, &str, u32, u32)] = &[\n");
    for (venue, symbol, span) in spans {
        s.push_str(&format!(
            "    ({venue:?}, {symbol:?}, {:?}, {}, {}),\n",
            span.timezone, span.start_hour, span.hours
        ));
    }
    s.push_str("];\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compute::MarketHoursProfile;
    use crate::{MarketHoursRow, Venue};
    use std::collections::BTreeMap;

    fn row(venue: Venue, sym: &str, gaps: usize, daily: &[u32]) -> MarketHoursRow {
        MarketHoursRow {
            venue,
            symbol: sym.to_string(),
            display_name: sym.to_string(),
            error: None,
            session: Err(crate::session::NoSpan::RoundTheClock),
            profile: MarketHoursProfile {
                total_gaps: gaps,
                attention_gaps: 0,
                midweek_attention_gaps: 0,
                midweek_fraction: 0.0,
                daily_close: !daily.is_empty(),
                daily_close_hours: daily.to_vec(),
                midweek_hour_hist: BTreeMap::new(),
            },
        }
    }

    #[test]
    fn renders_sorted_with_padded_hours() {
        let rows = vec![
            row(Venue::TradeNation, "CH20", 496, &[19, 20]),
            row(Venue::Oanda, "EUR_USD", 44, &[]),
        ];
        let out = render_table(&rows);
        // OANDA sorts before TN; EUR_USD is weekend-only (all sentinel).
        let oanda_idx = out.find("\"oanda\"").unwrap();
        let tn_idx = out.find("\"tradenation\"").unwrap();
        assert!(oanda_idx < tn_idx, "venues sorted");
        assert!(out.contains("[u32::MAX, u32::MAX, u32::MAX, u32::MAX, u32::MAX, u32::MAX]"));
        assert!(out.contains("[19, 20, u32::MAX, u32::MAX, u32::MAX, u32::MAX]"));
        assert!(out.contains("\"CH20\", true"), "enough gaps ⇒ reviewed");
    }

    #[test]
    fn few_samples_flagged_unreviewed() {
        let rows = vec![row(Venue::Oanda, "THIN", 5, &[])];
        let out = render_table(&rows);
        assert!(out.contains("\"THIN\", false"), "few gaps ⇒ unreviewed");
    }

    #[test]
    fn dedups_same_venue_symbol() {
        let rows = vec![
            row(Venue::Oanda, "DUP", 44, &[]),
            row(Venue::Oanda, "DUP", 44, &[]),
        ];
        let out = render_table(&rows);
        assert_eq!(out.matches("\"DUP\"").count(), 1, "duplicate key dropped");
    }

    #[test]
    fn only_instruments_with_a_span_get_a_session_row() {
        let mut spain = row(Venue::TradeNation, "Spain 35", 50, &[15]);
        spain.session = Ok(crate::session::SessionSpan {
            timezone: "Europe/Madrid".into(),
            start_hour: 9,
            hours: 9,
        });
        let fx = row(Venue::TradeNation, "EUR/USD", 50, &[]);
        let out = render_session_table(&[fx, spain.clone(), spain]);
        assert_eq!(
            out.matches("(\"tradenation\", \"Spain 35\", \"Europe/Madrid\", 9, 9),")
                .count(),
            1,
            "one de-duplicated row:\n{out}"
        );
        assert!(
            !out.contains("EUR/USD"),
            "a 24h market must have no row:\n{out}"
        );
    }
}
