//! Validate completed calibration evidence before generating runtime defaults.
use std::collections::BTreeSet;

use color_eyre::{Result, eyre::ensure};

use super::{InstrumentReport, Report};
use crate::compute::{MIN_INSTRUMENT_BARS, ReviewStatus};

/// A finished run may contain unavailable instruments. Keep those absent from
/// the runtime table, with their reasons retained in the committed evidence.
/// A checkpoint with unattempted symbols is always refused.
pub fn render_finished(report: &Report, account: &str, login: u64, server: &str) -> Result<String> {
    let wanted = report.requested_symbols.iter().collect::<BTreeSet<_>>();
    ensure!(
        wanted.len() == report.requested_symbols.len(),
        "duplicate requested instruments"
    );
    let attempted = report
        .instruments
        .iter()
        .map(|r| &r.symbol)
        .chain(report.failures.iter().map(|r| &r.symbol))
        .collect::<BTreeSet<_>>();
    ensure!(
        wanted == attempted && attempted.len() == report.instruments.len() + report.failures.len(),
        "calibration still has unattempted or duplicated instruments"
    );
    let eligible = report
        .instruments
        .iter()
        .filter(|row| {
            matches!(
                row.profile.review,
                ReviewStatus::Reviewed | ReviewStatus::MaskNotComputable
            )
        })
        .cloned()
        .collect::<Vec<_>>();
    let excluded = report
        .requested_symbols
        .iter()
        .filter(|symbol| !eligible.iter().any(|row| row.symbol == **symbol))
        .collect::<Vec<_>>();
    if !excluded.is_empty() {
        tracing::warn!(
            ?excluded,
            "MT5 instruments remain uncovered; no estimated spreads will be baked for them"
        );
    }
    let measured = Report {
        requested_symbols: eligible.iter().map(|row| row.symbol.clone()).collect(),
        instruments: eligible,
        complete: true,
        failures: vec![],
        ..report.clone()
    };
    render(&measured, account, login, server)
}

pub fn render(report: &Report, account: &str, login: u64, server: &str) -> Result<String> {
    validate_report(report, account, login, server)?;
    let mut rows = report.instruments.iter().collect::<Vec<_>>();
    rows.sort_by_key(|row| &row.symbol);
    let rendered = rows
        .into_iter()
        .map(|row| render_row(row, account))
        .collect::<Result<Vec<_>>>()?;
    Ok(format!(
        "// @generated by bake-mt5. Account={account}, login={login}, server={server}.\n\
         // Measured UTC window: {} through {}.\n\
         #[allow(clippy::type_complexity)]\n\
         pub static SPREAD_BASELINE_MT5: &[(&str, &str, &str, bool, u32, [f64; 24], f64, f64, f64, [f64; 24])] = &[\n{}];\n",
        report.from_utc,
        report.to_utc,
        rendered.join(""),
    ))
}

fn validate_report(report: &Report, account: &str, login: u64, server: &str) -> Result<()> {
    ensure!(
        account
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
            && !account.is_empty(),
        "invalid MT5 account name"
    );
    ensure!(report.schema_version == 1, "unsupported calibration schema");
    ensure!(
        report.feed == format!("mt5-{account}") && report.login == login && report.server == server,
        "calibration account identity mismatch"
    );
    ensure!(!server.contains(['\n', '\r']), "invalid server name");
    ensure!(
        report.complete && report.failures.is_empty(),
        "calibration is incomplete; failed instruments must be resolved before baking"
    );
    ensure!(
        report.to_utc - report.from_utc >= chrono::Duration::days(90),
        "baking requires at least 90 calendar days"
    );
    let wanted = report.requested_symbols.iter().collect::<BTreeSet<_>>();
    let got = report
        .instruments
        .iter()
        .map(|r| &r.symbol)
        .collect::<BTreeSet<_>>();
    ensure!(
        !wanted.is_empty()
            && wanted.len() == report.requested_symbols.len()
            && got.len() == report.instruments.len()
            && wanted == got,
        "calibration catalogue is incomplete or duplicated"
    );
    for row in &report.instruments {
        ensure!(
            row.first_minute_utc >= report.from_utc
                && row.last_minute_utc < report.to_utc
                && row.first_minute_utc <= row.last_minute_utc,
            "invalid measurement bounds for {}",
            row.symbol
        );
        validate_row(row)?;
    }
    Ok(())
}

fn validate_row(row: &InstrumentReport) -> Result<()> {
    let symbol = &row.symbol;
    let profile = &row.profile;
    ensure!(
        !symbol.is_empty() && symbol.is_ascii() && !symbol.chars().any(char::is_control),
        "invalid symbol"
    );
    ensure!(
        matches!(
            profile.review,
            ReviewStatus::Reviewed | ReviewStatus::MaskNotComputable
        ) && profile.n_bars >= MIN_INSTRUMENT_BARS,
        "insufficient reviewed data for {symbol}"
    );
    let asset = instrument_lookup::resolve(symbol)?
        .ok_or_else(|| color_eyre::eyre::eyre!("no metadata for {symbol}"))?;
    ensure!(
        asset.spread_schedule == row.schedule
            && asset.spread_schedule_tz().as_deref() == Some(row.timezone.as_str()),
        "spread schedule metadata changed for {symbol}"
    );
    ensure!(
        row.pip_size.is_finite() && row.pip_size > 0.0 && row.pip_size == asset.pip_size,
        "pip size metadata changed for {symbol}"
    );
    let values = profile
        .hour_widen_frac
        .iter()
        .chain(profile.hour_p90_frac.iter())
        .chain([
            &profile.baseline_low_pips,
            &profile.baseline_median_pips,
            &profile.baseline_high_pips,
        ]);
    ensure!(
        values.into_iter().all(|v| v.is_finite() && *v >= 0.0),
        "invalid spread values for {symbol}"
    );
    ensure!(
        profile.baseline_low_pips <= profile.baseline_median_pips
            && profile.baseline_median_pips <= profile.baseline_high_pips,
        "invalid spread percentiles for {symbol}"
    );
    ensure!(
        profile.elevated_hours >> 24 == 0 && profile.elevated_vec() == row.elevated_local_hours,
        "invalid hour mask for {symbol}"
    );
    ensure!(
        profile
            .hour_widen_frac
            .iter()
            .enumerate()
            .all(|(h, value)| if profile.elevated_hours & (1 << h) == 0 {
                *value == 0.0
            } else {
                *value == profile.hour_p90_frac[h]
            }),
        "widen and forecast disagree for {symbol}"
    );
    Ok(())
}

fn render_row(row: &InstrumentReport, account: &str) -> Result<String> {
    let profile = &row.profile;
    let key = format!("mt5:{account}:{}", row.symbol);
    // JSON string escaping is also valid Rust for these checked ASCII names.
    let key = serde_json::to_string(&key)?;
    let schedule = serde_json::to_string(&row.schedule)?;
    Ok(format!(
        "    (\"mt5-{account}\", {key}, {schedule}, true, {}, {:?}, {:?}, {:?}, {:?}, {:?}),\n",
        profile.elevated_hours,
        profile.hour_widen_frac,
        profile.baseline_median_pips,
        profile.baseline_low_pips,
        profile.baseline_high_pips,
        profile.hour_p90_frac
    ))
}

#[cfg(test)]
mod tests;
